import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'fr' | 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('fr');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('cena-language') as Language;
    if (savedLanguage && ['fr', 'en', 'pt'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('cena-language', language);
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      value = value?.[k];
    }

    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const translations = {
  fr: {
    common: {
      donate_now: 'Faire un don',
      read_more: 'Lire plus',
      learn_more: 'En savoir plus',
      show_less: 'Voir moins',
      contact_us: 'Nous contacter',
      get_involved: 'S\'impliquer',
      view_all: 'Voir tout',
      sign_up: 'S\'inscrire',
      join_us: 'Rejoignez-nous',
      trusted_by: 'Ils nous font confiance'
    },
    navigation: {
      home: 'Accueil',
      about: 'À propos',
      mission: 'Mission',
      vision: 'Vision',
      programs: 'Programmes',
      partners: 'Partenaires',
      members: 'Membres',
      events: 'Événements',
      team: 'Équipe',
      support: 'Soutien',
      blog: 'Blog',
      contact: 'Contact'
    },
    hero: {
      title: 'Héritage, Ambition & Excellence',
      subtitle: 'Canada — Excellence de la Diaspora',
      description: 'Forger l\'avenir de la diaspora angolaise et lusophone au Canada par l\'éducation stratégique, l\'entrepreneuriat innovant et un réseau d\'influence mondial.',
      cta_primary: 'Soutenez l\'Impact',
      cta_secondary: 'Nos Programmes',
      members_connected: 'Membres Connectés',
      active_programs: 'Programmes Actifs',
      partners: 'Partenaires Stratégiques',
      stat_members: '300+',
      stat_programs: '12',
      stat_partners: '20+'
    },
    about: {
      badge: 'L\'Essence de CENA',
      title: "Une Communauté d'Excellence & Impact",
      description: 'CENA incarne la force de la diaspora angolaise au Canada — une plateforme d\'excellence dédiée à l\'essor intellectuel et économique de notre héritage.',
      who_we_are: 'Qui nous sommes',
      who_we_are_text: 'Organisation d\'élite dédiée à l\'autonomisation de la diaspora lusophone par le mentorat, le leadership et l\'action collaborative de haut niveau.',
      our_approach: 'Notre Vision Stratégique',
      our_approach_text: 'Nous transformons l\'ambition en réalité grâce à un écosystème unique combinant éducation de pointe et synergie entrepreneuriale.',
      stats_title: 'Objectifs Stratégiques 2028',
      five_years_goals: "Nos Objectifs d'ici cinq ans",
      stats: {
        members: 'Membres Actifs',
        workshops: 'Ateliers Leaders',
        partnerships: 'Alliances Stratégiques',
        years: 'Excellence & Impact',
        badge_impact: 'Professionnalisme'
      }
    },
    mission: {
      badge: 'Notre Engagement',
      title: 'Bâtir un Héritage Durable',
      description: 'Notre mission transcende l\'entraide : nous créons les leaders de demain à travers un accompagnement sur mesure.',
      pillar1_title: 'Ingénierie de l\'Éducation',
      pillar1_desc: 'Accès à des ressources de calibre mondial pour le développement de l\'expertise et de la pensée innovante.',
      pillar2_title: 'Écosystème Entrepreneuriat',
      pillar2_desc: 'Catalyseur de succès pour les entreprises lusophones, du démarrage à l\'expansion internationale.',
      pillar3_title: 'Réseau d\'Influence',
      pillar3_desc: 'Connexions de haut niveau ouvrant les portes des marchés canadiens et internationaux.'
    },
    vision: {
      badge: 'Horizon 2030',
      title: 'Devenir le Pilier de la Diaspora',
      description: 'Nous aspirons à être la référence indiscutable pour l\'intégration et le succès des talents lusophones en Amérique du Nord.',
      goal1: 'Souveraineté Éducative',
      goal1_desc: 'Programmes certifiés d\'excellence favorisant une réussite académique et professionnelle sans précédent.',
      goal2: 'Leadership Économique',
      goal2_desc: 'Propulser la croissance durable à travers des fonds et des conseils stratégiques pour entrepreneurs.',
      goal3: 'Cohésion & Prestige',
      goal3_desc: 'Rayonnement de la culture angolaise à travers des succès concrets et une influence durable.',
      read_objective: 'Lire l\'Objectif'
    },
    programs: {
      badge: 'Écosystème CENA',
      title: 'Programmes de Transformation',
      description: 'Des piliers stratégiques conçus pour chaque étape de votre parcours : de l\'étudiant passionné au PDG influent.',
      academy_title: 'CENA Academy',
      academy_description: 'Masterclass et formations certifiantes pour l\'élite de demain.',
      academy_details: 'Un curriculum rigoureux couvrant la gestion, la technologie et les soft skills nécessaires pour exceller dans le marché canadien.',
      academy_impact: 'Éducation',
      women_title: 'Élite Féminine',
      women_description: 'Catalyseur de leadership pour les femmes influentes de la communauté.',
      women_details: 'Un espace dédié pour briser les plafonds de verre, favoriser le networking stratégique et le développement du leadership féminin.',
      women_impact: 'Leadership',
      youth_title: 'Génération Innovation',
      youth_description: 'Former les pionniers technologiques et créatifs de la diaspora.',
      youth_details: 'Programmes immersifs en codage, design et innovation pour préparer la jeunesse aux métiers du futur.',
      youth_impact: 'Innovation',
      mentorship_title: 'Cercle de Mentorat',
      mentorship_description: 'Apprendre des plus grands pour accélérer votre propre ascension.',
      mentorship_details: 'Mise en relation directe avec des cadres et entrepreneurs établis pour un transfert de connaissances et d\'expérience critique.',
      mentorship_impact: 'Mentorat',
      entrepreneurship_title: 'HUB Entrepreneur',
      entrepreneurship_description: 'Accélérateur de croissance et mentorat pour entreprises ambitieuses.',
      entrepreneurship_details: 'Accompagnement de A à Z : du business plan à la levée de fonds et au développement de marché.',
      entrepreneurship_impact: 'Affaires',
      integration_title: 'Intégration & Essor',
      integration_description: 'Parcours d\'accueil privilégié pour une insertion rapide et réussie.',
      integration_details: 'Support administratif, linguistique et culturel pour transformer l\'immigration en une transition fluide vers le succès.',
      integration_impact: 'Social',
      events_title: 'Sommets & Ateliers',
      events_description: 'Échanges de haut niveau et intelligence collective en action.',
      events_details: 'Organisation d\'événements d\'influence réunissant experts mondiaux et talents locaux.',
      events_impact: 'Networking',
      volunteer_title: 'Programme de Bénévolat',
      volunteer_description: 'Opportunités de contribuer et de faire une différence ensemble.',
      volunteer_details: 'Rejoignez notre réseau de leaders et d\'experts pour soutenir les initiatives de la diaspora angolaise au Canada.',
      volunteer_impact: 'Impact',
      join_program_title: 'Prêt à Recommander l\'Excellence?',
      join_program_description: 'Que vous soyez étudiant, entrepreneur ou expert, votre place est parmi nous.',
      join_program_button: 'Devenir Membre'
    },
    partners: {
      badge: 'Alliances',
      title: 'Construire l\'Avenir Ensemble',
      description: 'Nous collaborons avec des institutions de prestige pour démultiplier l\'impact de nos initiatives.',
      partner_type_corporate: 'Partenaires Corporatifs',
      partner_type_community: 'Organisations Communautaires',
      partner_type_educational: 'Institutions Éducatives',
      partner_type_government: 'Soutien Institutionnel',
      become_partner_title: 'Devenir Partenaire Stratégique',
      become_partner_desc: 'Joignez vos forces à CENA pour catalyser le succès de la diaspora lusophone au Canada.',
      become_partner_button: 'Initier un Partenariat'
    },
    members: {
      badge: 'Cercle CENA',
      title: 'Une Communauté d\'Élite',
      description: 'Ingénieurs, artistes, entrepreneurs et étudiants unis par la quête de l\'excellence.',
      benefit1: 'Accès exclusif au réseau de mentorat CENA.',
      benefit2: 'Tarifs préférentiels pour nos sommets annuels.',
      benefit3: 'Accès prioritaire à notre plateforme de recrutement.',
      benefit4: 'Invitations à des ateliers de leadership privés.',
      benefit5: 'Publication de vos succès dans notre newsletter.',
      benefit6: 'Soutien administratif pour l\'entrepreneuriat.',
      join_title: 'Rejoindre l\'Avant-Garde',
      join_desc: 'Unissez-vous à un réseau dynamique où chaque parcours individuel nourrit notre ambition collective.',
      join_button: 'Obtenir ma Carte de Membre'
    },
    events: {
      badge: 'Calendrier',
      title: 'Événements Stratégiques',
      description: 'Des rendez-vous exclusifs pour expandre votre réseau et vos connaissances.',
      upcoming: 'Sommets à Venir',
      register_now: 'Réserver ma place',
      type_workshop: 'Atelier Expert',
      type_networking: 'Networking Élite',
      type_cultural: 'Célébration Prestige',
      event1_title: 'Intelligence Artificielle & Entrepreneuriat',
      event1_description: 'Comprendre comment l\'IA transforme les modèles d\'affaires modernes.',
      event1_location: 'Montréal HQ',
      event2_title: 'Sommet des Leaders Diaspora',
      event2_description: 'Rencontre annuelle des entrepreneurs et influenceurs lusophones au Canada.',
      event2_location: 'Toronto Centre',
      event3_title: 'Gala de l\'Excellence Angolane',
      event3_description: 'Une soirée de prestige célébrant nos réussites culturelles et économiques.',
      event3_location: 'Hôtel Hilton',
      coming_soon: 'À Déterminer',
      past_events: 'Héritage d\'Événements',
      past_event_success: 'Tous les sommets organisés avec un taux de satisfaction de 98%.',
      explore_calendar: 'Voir l\'Agenda Complet',
      register: 'S\'inscrire'
    },
    team: {
      badge: 'Gouvernance',
      title: 'Conseil d\'Administration',
      description: 'Une équipe visionnaire dédiée au rayonnement de la diaspora angolaise.',
      leadership_title: 'Vision de la Présidence',
      leadership_message: 'Notre force réside dans notre unité et notre volonté d\'exceller ensemble.',
      role_president: 'Présidente & Fondatrice',
      role_vp_operations: 'Vice-Présidente des Opérations',
      role_finance: 'Directeur Financier',
      role_international: 'Relations Internationales',
      role_youth: 'Développement de la Jeunesse',
      role_hr: 'Ressources Humaines',
      council_member: 'Membre du Conseil'
    },
    support: {
      badge: 'Investissement',
      title: 'Soutenez la Nouvelle Élite',
      description: 'Votre contribution directe finance les bourses et les infrastructures de croissance.',
      donation_title: 'Don Ponctuel',
      donation_description: 'Soutien immédiat pour nos actions urgentes.',
      volunteer_title: 'Bénévolat Leader',
      volunteer_description: 'Engagez votre temps et vos compétences.',
      sponsor_title: 'Sponsoring Corporatif',
      sponsor_description: 'Associez votre marque à l\'excellence.',
      donate_title: 'Investir dans le Futur',
      donate_description: 'Chaque don est un pilier pour nos académies et nos programmes d\'accélération.',
      choose_amount: 'Montant de l\'investissement ($)',
      tax_notice: 'Reçus officiels pour déduction fiscale disponibles.',
      secure_payment: 'Transaction sécurisée via PayPal',
      financial_scaling: 'Support à la Croissance Financière',
      contribution_center: 'Centre de Contribution',
      initiate_contribution: 'Initier ma Contribution',
      impact_50: 'Équipement pour un étudiant créatif',
      impact_100: 'Accès à un module de Masterclass',
      impact_250: 'Soutien à une startup locale',
      impact_500: 'Bourse d\'Excellence Completa'
    },
    get_involved: {
      badge: 'Impact',
      title: 'Façonnez l\'Avenir avec Nous',
      description: 'Il existe plusieurs façons de contribuer au rayonnement de notre communauté.',
      donate_title: 'Soutien Financier',
      donate_description: 'Investissez dans nos futurs leaders et entrepreneurs.',
      volunteer_title: 'Partage d\'Expertise',
      volunteer_description: 'Devenez mentor ou bénévole lors de nos sommets.',
      membership_title: 'Devenir Membre',
      membership_description: 'Rejoignez le réseau professionnel le plus influent de la diaspora.',
      choose_amount: 'Montant du don',
      custom_amount: 'Autre montant',
      donation_message: 'Votre message (optionnel)',
      donation_message_placeholder: 'Dites-nous ce qui vous inspire...',
      anbi_notice: 'CENA est un organisme à but non lucratif reconnu au Canada.',
      other_ways: 'Autres manières de s\'impliquer',
      impact_title: 'Votre Impact Concret',
      impact_25: 'Matériel pédagogique pour un étudiant',
      impact_50: 'Accès à un atelier de leadership',
      impact_100: 'Financement partiel d\'un projet innovant',
      impact_250: 'Bourse de mentorat complète'
    },
    blog: {
      badge: 'Actualités',
      title: 'Perspectives & Insights',
      description: 'Décryptage et témoignages de la réussite lusophone au Canada.',
      read_full: 'Lire l\'analyse complète',
      newsletter_title: 'Restez Informé',
      newsletter_description: 'Rejoignez notre cercle restreint pour des mises à jour exclusives sur notre impact mondial.',
      subscribe_button: 'S\'abonner',
      read_entry: 'Lire l\'Article',
      subscription_active: 'Abonnement Actif',
      intel_distribution: 'Distribution d\'Informations Privées',
      email_placeholder: 'VOTRE EMAIL',
      article1_title: 'Lancement de l\'Incubateur CENA',
      article1_excerpt: 'Comment nous transformons l\'ambition en succès concret pour les nouveaux entrepreneurs.',
      article1_author: 'Direction CENA',
      article1_category: 'Entrepreneuriat',
      article2_title: 'Intelligence Collective en Action',
      article2_excerpt: 'Retour sur notre dernière soirée de networking qui a généré plus de 15 collaborations.',
      article2_author: 'Coordinateur Réseau',
      article2_category: 'Networking',
      article3_title: 'Alliances Éducatives 2025',
      article3_excerpt: 'De nouveaux partenariats avec des institutions de prestige pour nos boursiers.',
      article3_author: 'Pôle Éducation',
      article3_category: 'Éducation'
    },
    gallery: {
      badge: 'Moments',
      title: 'Célébrations & Succès',
      subtitle: 'Retours en images sur nos derniers rassemblements prestigieux',
      view_all: 'Galerie Complète',
      explore_instruction: 'Glissez ou cliquez pour explorer'
    },
    subject: {
      label: 'Objet',
      placeholder: 'Sélectionner un objet',
      membership: 'Devenir membre',
      volunteer: 'Bénévolat',
      partnership: 'Partenariat',
      sponsorship: 'Sponsoring',
      other: 'Autre'
    },
    footer: {
      contact_bureau: 'Contact Bureau',
      follow_us: 'Suivez-nous',
      get_in_touch: 'Contact & Accès',
      our_location: 'Siège Social',
      location_text: '3181 Montée Saint-hubert, QC, Canada',
      phone: 'Téléphone Office',
      email: 'Liaison Directe',
      about_cena: 'Mission Institutionnelle',
      about_text: 'CENA est l\'organisme de référence pour le rayonnement angolais et lusophone au Canada.',
      send_message: 'Liaison Stratégique',
      your_name: 'Nom complet',
      your_email: 'Adresse courriel',
      subject: 'Objet de la demande',
      your_message: 'Votre message ou proposition',
      send_message_btn: 'Transmettre la demande',
      quick_links: 'Navigation Rapide',
      legal: 'Mentions Légales',
      privacy_policy: 'Confidentialité des données',
      terms_of_service: 'Conditions générales',
      description: 'L\'Excellence, l\'Ambition et l\'Héritage au service d\'une communauté rayonnante.',
      copyright: '© 2025 CENA - Comunidade de Educação e Networking Angolana. Tous droits réservés.',
      built_with_love: 'Propulsé par l\'intelligence collective.'
    }
  },
  en: {
    common: {
      donate_now: 'Donate Now',
      read_more: 'Read More',
      learn_more: 'Learn More',
      show_less: 'Show Less',
      contact_us: 'Contact Us',
      get_involved: 'Get Involved',
      view_all: 'View All',
      sign_up: 'Sign Up',
      join_us: 'Join Us',
      trusted_by: 'Trusted By'
    },
    navigation: {
      home: 'Home',
      about: 'About',
      mission: 'Mission',
      vision: 'Vision',
      programs: 'Programs',
      partners: 'Partners',
      members: 'Members',
      events: 'Events',
      team: 'Team',
      support: 'Support',
      blog: 'Blog',
      contact: 'Contact'
    },
    hero: {
      title: 'Heritage, Ambition & Excellence',
      subtitle: 'Canada — Diaspora Excellence',
      description: 'Forging the future of the Angolan and Lusophone diaspora in Canada through strategic education, innovative entrepreneurship, and a global influence network.',
      cta_primary: 'Support the Impact',
      cta_secondary: 'Our Programs',
      members_connected: 'Connected Members',
      active_programs: 'Active Programs',
      partners: 'Strategic Partners',
      stat_members: '300+',
      stat_programs: '12',
      stat_partners: '20+'
    },
    about: {
      badge: 'The Essence of CENA',
      title: 'A Community of Excellence & Impact',
      description: 'CENA embodies the power of the Angolan diaspora in Canada — a platform of excellence dedicated to the intellectual and economic rise of our heritage.',
      who_we_are: 'Who We Are',
      who_we_are_text: 'An elite organization dedicated to empowering the Lusophone diaspora through high-level mentoring, leadership, and collaborative action.',
      our_approach: 'Our Strategic View',
      our_approach_text: 'We transform ambition into reality through a unique ecosystem combining leading-edge education and entrepreneurial synergy.',
      stats_title: 'Strategic Goals 2028',
      five_years_goals: 'Our Goals for the Next Five Years',
      stats: {
        members: 'Active Members',
        workshops: 'Leader Workshops',
        partnerships: 'Strategic Alliances',
        years: 'Excellence & Impact',
        badge_impact: 'Professionalism'
      }
    },
    mission: {
      badge: 'Our Commitment',
      title: 'Building a Lasting Legacy',
      description: 'Our mission goes beyond mutual aid: we create the leaders of tomorrow through tailored support.',
      pillar1_title: 'Education Engineering',
      pillar1_desc: 'Access to world-class resources for developing expertise and innovative thinking.',
      pillar2_title: 'Entrepreneurship Ecosystem',
      pillar2_desc: 'Catalyst for Lusophone business success, from startup to international expansion.',
      pillar3_title: 'Influence Network',
      pillar3_desc: 'High-level connections opening doors to Canadian and international markets.'
    },
    vision: {
      badge: 'Horizon 2030',
      title: 'Becoming the Diaspora Pillar',
      description: 'We aspire to be the indisputable reference for the integration and success of Lusophone talents in North America.',
      goal1: 'Educational Sovereignty',
      goal1_desc: 'Certified programs of excellence fostering unprecedented academic and professional success.',
      goal2: 'Economic Leadership',
      goal2_desc: 'Propelling sustainable growth through strategic funds and advice for entrepreneurs.',
      goal3: 'Cohesion & Prestige',
      goal3_desc: 'Shining Angolan culture through concrete success and lasting influence.',
      read_objective: 'Read Objective'
    },
    programs: {
      badge: 'CENA Ecosystem',
      title: 'Transformation Programs',
      description: 'Strategic pillars designed for every step of your journey: from passionate student to influential CEO.',
      academy_title: 'CENA Academy',
      academy_description: 'Masterclasses and certifying training for tomorrow\'s elite.',
      academy_details: 'A rigorous curriculum covering management, technology, and soft skills needed to excel in the Canadian market.',
      academy_impact: 'Education',
      women_title: 'Elite Women',
      women_description: 'Leadership catalyst for the community\'s influential women.',
      women_details: 'A dedicated space to break glass ceilings, foster strategic networking, and female leadership development.',
      women_impact: 'Leadership',
      youth_title: 'Innovation Generation',
      youth_description: 'Training the technological and creative pioneers of the diaspora.',
      youth_details: 'Immersive programs in coding, design, and innovation to prepare youth for future careers.',
      youth_impact: 'Innovation',
      mentorship_title: 'Mentoring Circle',
      mentorship_description: 'Learn from the greatest to accelerate your own ascent.',
      mentorship_details: 'Direct connection with established executives and entrepreneurs for critical knowledge and experience transfer.',
      mentorship_impact: 'Mentorship',
      entrepreneurship_title: 'Entrepreneur HUB',
      entrepreneurship_description: 'Growth accelerator and mentoring for ambitious businesses.',
      entrepreneurship_details: 'End-to-end support: from business plans to fundraising and market development.',
      entrepreneurship_impact: 'Business',
      integration_title: 'Integration & Rise',
      integration_description: 'Privileged welcome path for quick and successful integration.',
      integration_details: 'Administrative, linguistic, and cultural support to turn immigration into a smooth transition to success.',
      integration_impact: 'Social',
      events_title: 'Summits & Workshops',
      events_description: 'High-level exchanges and collective intelligence in action.',
      events_details: 'Organizing influential events bringing together global experts and local talents.',
      events_impact: 'Networking',
      volunteer_title: 'Volunteer Program',
      volunteer_description: 'Opportunities to contribute and make a difference together.',
      volunteer_details: 'Join our network of leaders and experts to support Angolan diaspora initiatives in Canada.',
      volunteer_impact: 'Impact',
      join_program_title: 'Ready to Recommend Excellence?',
      join_program_description: 'Whether you are a student, entrepreneur, or expert, your place is with us.',
      join_program_button: 'Become a Member'
    },
    partners: {
      badge: 'Alliances',
      title: 'Building the Future Together',
      description: 'We collaborate with prestigious institutions to multiply the impact of our initiatives.',
      partner_type_corporate: 'Corporate Partners',
      partner_type_community: 'Community Organizations',
      partner_type_educational: 'Educational Institutions',
      partner_type_government: 'Institutional Support',
      become_partner_title: 'Become a Strategic Partner',
      become_partner_desc: 'Join forces with CENA to catalyze the success of the Lusophone diaspora in Canada.',
      become_partner_button: 'Initiate a Partnership'
    },
    members: {
      badge: 'CENA Circle',
      title: 'An Elite Community',
      description: 'Engineers, artists, entrepreneurs, and students united by the quest for excellence.',
      benefit1: 'Exclusive access to the CENA mentoring network.',
      benefit2: 'Preferential rates for our annual summits.',
      benefit3: 'Priority access to our recruitment platform.',
      benefit4: 'Invitations to private leadership workshops.',
      benefit5: 'Publication of your successes in our newsletter.',
      benefit6: 'Administrative support for entrepreneurship.',
      join_title: 'Join the Avant-Garde',
      join_desc: 'Unite with a dynamic network where each individual journey feeds our collective ambition.',
      join_button: 'Get My Member Card'
    },
    events: {
      badge: 'Schedule',
      title: 'Strategic Events',
      description: 'Exclusive appointments to expand your network and knowledge.',
      upcoming: 'Upcoming Summits',
      register_now: 'Book My Seat',
      type_workshop: 'Expert Workshop',
      type_networking: 'Elite Networking',
      type_cultural: 'Prestige Celebration',
      event1_title: 'AI & Entrepreneurship',
      event1_description: 'Understanding how AI is transforming modern business models.',
      event1_location: 'Montreal HQ',
      event2_title: 'Diaspora Leaders Summit',
      event2_description: 'Annual meeting of Lusophone entrepreneurs and influencers in Canada.',
      event2_location: 'Toronto Center',
      event3_title: 'Angolan Excellence Gala',
      event3_description: 'A prestigious evening celebrating our cultural and economic achievements.',
      event3_location: 'Hilton Hotel',
      coming_soon: 'TBA',
      past_events: 'Legacy of Events',
      past_event_success: 'All summits organized with a 98% satisfaction rate.',
      explore_calendar: 'View Full Calendar',
      register: 'Register'
    },
    team: {
      badge: 'Governance',
      title: 'Board of Directors',
      description: 'A visionary team dedicated to the radiance of the Angolan diaspora.',
      leadership_title: 'President\'s Vision',
      leadership_message: 'Our strength lies in our unity and our will to excel together.',
      role_president: 'President & Founder',
      role_vp_operations: 'VP of Operations',
      role_finance: 'Financial Director',
      role_international: 'International Relations',
      role_youth: 'Youth Development',
      role_hr: 'Human Resources',
      council_member: 'Council Member'
    },
    support: {
      badge: 'Investment',
      title: 'Support the New Elite',
      description: 'Your direct contribution funds scholarships and growth infrastructure.',
      donation_title: 'One-time Donation',
      donation_description: 'Immediate support for our urgent actions.',
      volunteer_title: 'Leader Volunteering',
      volunteer_description: 'Engage your time and skills.',
      sponsor_title: 'Corporate Sponsoring',
      sponsor_description: 'Associate your brand with excellence.',
      donate_title: 'Invest in the Future',
      donate_description: 'Every donation is a pillar for our academies and acceleration programs.',
      choose_amount: 'Investment Amount ($)',
      tax_notice: 'Official tax receipts available.',
      secure_payment: 'Secure transition via PayPal',
      financial_scaling: 'Financial Growth Support',
      contribution_center: 'Contribution Center',
      initiate_contribution: 'Initiate My Contribution',
      impact_50: 'Equipment for a creative student',
      impact_100: 'Access to a Masterclass module',
      impact_250: 'Support for a local startup',
      impact_500: 'Full Excellence Scholarship'
    },
    get_involved: {
      badge: 'Impact',
      title: 'Shape the Future with Us',
      description: 'There are many ways to contribute to our community\'s influence.',
      donate_title: 'Financial Support',
      donate_description: 'Invest in our future leaders and entrepreneurs.',
      volunteer_title: 'Expertise Sharing',
      volunteer_description: 'Become a mentor or volunteer at our summits.',
      membership_title: 'Become a Member',
      membership_description: 'Join the most influential professional network of the diaspora.',
      choose_amount: 'Donation Amount',
      custom_amount: 'Other Amount',
      donation_message: 'Your Message (optional)',
      donation_message_placeholder: 'Tell us what inspires you...',
      anbi_notice: 'CENA is a recognized non-profit organization in Canada.',
      other_ways: 'Other Ways to Get Involved',
      impact_title: 'Your Concrete Impact',
      impact_25: 'Teaching material for one student',
      impact_50: 'Access to a leadership workshop',
      impact_100: 'Partial funding for an innovative project',
      impact_250: 'Full mentoring scholarship'
    },
    blog: {
      badge: 'News',
      title: 'Perspectives & Insights',
      description: 'Decrypting stories and testimonies of Lusophone success in Canada.',
      read_full: 'Read Full Analysis',
      newsletter_title: 'Stay Informed',
      newsletter_description: 'Join our inner circle for exclusive updates on our global impact.',
      subscribe_button: 'Subscribe',
      read_entry: 'Read Entry',
      subscription_active: 'Subscription Active',
      intel_distribution: 'Private Intel Distribution',
      email_placeholder: 'ENTER EMAIL',
      article1_title: 'CENA Incubator Launch',
      article1_excerpt: 'How we transform ambition into concrete success for new entrepreneurs.',
      article1_author: 'CENA Leadership',
      article1_category: 'Entrepreneurship',
      article2_title: 'Collective Intelligence in Action',
      article2_excerpt: 'Looking back at our latest networking evening that sparked over 15 collaborations.',
      article2_author: 'Network Coordinator',
      article2_category: 'Networking',
      article3_title: 'Educational Alliances 2025',
      article3_excerpt: 'New partnerships with prestigious institutions for our scholarship holders.',
      article3_author: 'Education Hub',
      article3_category: 'Education'
    },
    gallery: {
      badge: 'Moments',
      title: 'Celebrations & Success',
      subtitle: 'A look back at our recent prestigious gatherings',
      view_all: 'Full Gallery',
      explore_instruction: 'Drag or click to explore'
    },
    subject: {
      label: 'Subject',
      placeholder: 'Select a subject',
      membership: 'Become a member',
      volunteer: 'Volunteer',
      partnership: 'Partnership',
      sponsorship: 'Sponsoring',
      other: 'Other'
    },
    footer: {
      contact_bureau: 'Office Contact',
      follow_us: 'Follow Us',
      get_in_touch: 'Contact & Access',
      our_location: 'Headquarters',
      location_text: '3181 Montée Saint-hubert, QC, Canada',
      phone: 'Office Phone',
      email: 'Direct Liaison',
      about_cena: 'Institutional Mission',
      about_text: 'CENA is the reference for the Angolan and Lusophone radiance in Canada.',
      send_message: 'Strategic Liaison',
      your_name: 'Full Name',
      your_email: 'Email Address',
      subject: 'Subject of Request',
      your_message: 'Your Message or Proposal',
      send_message_btn: 'Transmit Request',
      quick_links: 'Quick Links',
      legal: 'Legal Notice',
      privacy_policy: 'Data Privacy',
      terms_of_service: 'Terms & Conditions',
      description: 'Excellence, Ambition, and Heritage at the service of a radiant community.',
      copyright: '© 2025 CENA - Comunidade de Educação e Networking Angolana. All rights reserved.',
      built_with_love: 'Powered by collective intelligence.'
    }
  },
  pt: {
    common: {
      donate_now: 'Doar Agora',
      read_more: 'Ler Mais',
      learn_more: 'Saber Mais',
      show_less: 'Ver Menos',
      contact_us: 'Contacte-nos',
      get_involved: 'Participar',
      view_all: 'Ver Tudo',
      sign_up: 'Inscrever-se',
      join_us: 'Junte-se a Nós',
      trusted_by: 'Eles Confiam em Nós'
    },
    navigation: {
      home: 'Início',
      about: 'Sobre',
      mission: 'Missão',
      vision: 'Visão',
      programs: 'Programas',
      partners: 'Parceiros',
      members: 'Membros',
      events: 'Eventos',
      team: 'Equipa',
      support: 'Apoio',
      blog: 'Blog',
      contact: 'Contacto'
    },
    hero: {
      title: 'Herança, Ambição & Excelência',
      subtitle: 'Canadá — Excelência da Diáspora',
      description: 'Forjando o futuro da diáspora angolana e lusófona no Canadá através da educação estratégica, empreendedorismo inovador e uma rede de influência global.',
      cta_primary: 'Apoie o Impacto',
      cta_secondary: 'Nossos Programas',
      members_connected: 'Membros Conectados',
      active_programs: 'Programas Ativos',
      partners: 'Parceiros Estratégicos',
      stat_members: '300+',
      stat_programs: '12',
      stat_partners: '20+'
    },
    about: {
      badge: 'A Essência da CENA',
      title: 'Uma Comunidade de Excelência & Impacto',
      description: 'A CENA encarna a força da diáspora angolana no Canadá — uma plataforma de excelência dedicada ao desenvolvimento intelectual e económico da nossa herança.',
      who_we_are: 'Quem Somos',
      who_we_are_text: 'Organização de elite dedicada ao empoderamento da diáspora lusófona através de mentoria, liderança e ação colaborativa de alto nível.',
      our_approach: 'Visto Estratégica',
      our_approach_text: 'Transformamos ambição em realidade através de um ecossistema único que combina educação de ponta e sinergia empreendedora.',
      stats_title: 'Metas Estratégicas 2028',
      five_years_goals: 'Nossos Objetivos para os Próximos Cinco Anos',
      stats: {
        members: 'Membros Ativos',
        workshops: 'Workshops Líderes',
        partnerships: 'Alianças Estratégicas',
        years: 'Excelência & Impacto',
        badge_impact: 'Profissionalismo'
      }
    },
    mission: {
      badge: 'Nosso Compromisso',
      title: 'Construindo um Legado Duradouro',
      description: 'A nossa missão transcende a ajuda mútua: criamos os líderes de amanhã através de um acompanhamento personalizado.',
      pillar1_title: 'Engenharia da Educação',
      pillar1_desc: 'Acesso a recursos de classe mundial para o desenvolvimento de perícia e pensamento inovador.',
      pillar2_title: 'Ecossistema de Empreendedorismo',
      pillar2_desc: 'Catalisador de sucesso para empresas lusófonas, desde o arranque à expansão internacional.',
      pillar3_title: 'Rede de Influência',
      pillar3_desc: 'Conexões de alto nível que abrem as portas dos mercados canadianos e internacionais.'
    },
    vision: {
      badge: 'Horizonte 2030',
      title: 'Tornar-se o Pilar da Diáspora',
      description: 'Aspiramos a ser a referência indiscutível para a integração e o sucesso dos talentos lusófonos na América do Norte.',
      goal1: 'Soberania Educativa',
      goal1_desc: 'Programas certificados de excelência que promovem um sucesso académico e profissional sem precedentes.',
      goal2: 'Liderança Económica',
      goal2_desc: 'Propulsionar o crescimento sustentável através de fundos estratégicos e aconselhamento para empreendedores.',
      goal3: 'Coesão & Prestígio',
      goal3_desc: 'Divulgação da cultura angolana através de sucessos concretos e uma influência duradoura.',
      read_objective: 'Ler Objetivo'
    },
    programs: {
      badge: 'Ecossistema CENA',
      title: 'Programmes de Transformação',
      description: 'Pilares estratégicos concebidos para cada etapa do seu percurso: do estudante apaixonado ao CEO influente.',
      academy_title: 'Académie CENA',
      academy_description: 'Masterclasses e formações certificadas para a elite de amanhã.',
      academy_details: 'Um currículo rigoroso cobrindo gestão, tecnologia e soft skills necessárias para se destacar no mercado canadense.',
      academy_impact: 'Educação',
      women_title: 'Elite Feminina',
      women_description: 'Catalisador de liderança para as mulheres influentes da comunidade.',
      women_details: 'Um espaço dedicado para quebrar tetos de vidro, promover networking estratégico e o desenvolvimento da liderança feminina.',
      women_impact: 'Liderança',
      youth_title: 'Geração Inovação',
      youth_description: 'Formar os pioneiros tecnológicos e créatifs da diáspora.',
      youth_details: 'Programmas imersivos em codificação, design e inovação para preparar os jovens para as profissões do futuro.',
      youth_impact: 'Inovação',
      mentorship_title: 'Círculo de Mentoria',
      mentorship_description: 'Aprender com os melhores para acelerar a sua própria ascensão.',
      mentorship_details: 'Conexão direta com executivos e empresários estabelecidos para uma transferência crítica de conhecimento e experiência.',
      mentorship_impact: 'Mentoria',
      entrepreneurship_title: 'HUB Empreendedor',
      entrepreneurship_description: 'Acelerador de crescimento e mentoria para empresas ambiciosas.',
      entrepreneurship_details: 'Acompanhamento ponta a ponta: do plano de negócios à captação de recursos e desenvolvimento de mercado.',
      entrepreneurship_impact: 'Negócios',
      integration_title: 'Integração & Ascensão',
      integration_description: 'Percurso de acolhimento privilegiado para uma inserção rápida e bem-sucedida.',
      integration_details: 'Apoio administrativo, linguístico e cultural para transformar a imigração em uma transição suave para o sucesso.',
      integration_impact: 'Social',
      events_title: 'Cimeiras & Workshops',
      events_description: 'Intercâmbios de alto nível e inteligência coletiva em ação.',
      events_details: 'Organização de eventos influentes reunindo especialistas globais e talentos locais.',
      events_impact: 'Networking',
      volunteer_title: 'Programa de Voluntariado',
      volunteer_description: 'Oportunidades para contribuir e fazer a diferença juntos.',
      volunteer_details: 'Junte-se à nossa rede de líderes e especialistas para apoiar as iniciativas da diáspora angolana no Canadá.',
      volunteer_impact: 'Impacto',
      join_program_title: 'Pronto para Recomendar Excelência?',
      join_program_description: 'Quer seja estudante, empreendedor ou especialista, o seu lugar é connosco.',
      join_program_button: 'Torne-se Membro'
    },
    partners: {
      badge: 'Alianças',
      title: 'Construindo o Futuro Juntos',
      description: 'Colaboramos com instituições de prestígio para multiplicar o impacto das nossas iniciativas.',
      partner_type_corporate: 'Parceiros Corporativos',
      partner_type_community: 'Organizações Comunitárias',
      partner_type_educational: 'Instituições Educativas',
      partner_type_government: 'Apoio Institucional',
      become_partner_title: 'Tornar-se Parceiro Estratégico',
      become_partner_desc: 'Junte forças com a CENA para catalisar o sucesso da diáspora lusófona no Canadá.',
      become_partner_button: 'Iniciar Parceria'
    },
    members: {
      badge: 'Círculo CENA',
      title: 'Uma Comunidade de Elite',
      description: 'Engenheiros, artistas, empreendedores e estudantes unidos pela busca da excelência.',
      benefit1: 'Acesso exclusivo à rede de mentoria CENA.',
      benefit2: 'Taxas preferenciais para as nossas cimeiras anuais.',
      benefit3: 'Acesso prioritário à nossa plataforma de recrutamento.',
      benefit4: 'Convites para workshops de liderança privados.',
      benefit5: 'Publicação dos seus sucessos na nossa newsletter.',
      benefit6: 'Apoio administrativo para o empreendedorismo.',
      join_title: 'Junte-se à Vanguarda',
      join_desc: 'Una-se a uma rede dinâmica onde cada percurso individual alimenta a nossa ambição coletiva.',
      join_button: 'Obter o Meu Cartão de Membro'
    },
    events: {
      badge: 'Calendário',
      title: 'Eventos Estratégicos',
      description: 'Encontros exclusivos para expandir a sua rede e os seus conhecimentos.',
      upcoming: 'Próximas Cimeiras',
      register_now: 'Reservar o meu lugar',
      type_workshop: 'Workshop Especialista',
      type_networking: 'Networking de Elite',
      type_cultural: 'Célébração de Prestígio',
      event1_title: 'IA & Empreendedorismo',
      event1_description: 'Compreender como a IA está a transformar os modelos de negócio modernos.',
      event1_location: 'Sede Montreal',
      event2_title: 'Cimeira de Líderes da Diáspora',
      event2_description: 'Encontro anual de empreendedores e influenciadores lusófonos no Canadá.',
      event2_location: 'Centro Toronto',
      event3_title: 'Gala da Excelência Angolana',
      event3_description: 'Uma noite de prestígio celebrando as nossas conquistas culturais e económicas.',
      event3_location: 'Hotel Hilton',
      coming_soon: 'A Definir',
      past_events: 'Legado de Eventos',
      past_event_success: 'Todas as cimeiras organizadas com uma taxa de satisfação de 98%.',
      explore_calendar: 'Ver Agenda Completas',
      register: 'Inscrever-se'
    },
    team: {
      badge: 'Governança',
      title: 'Conselho de Administração',
      description: 'Uma equipa visionária dedicada ao prestígio da diáspora angolana.',
      leadership_title: 'Visão da Presidência',
      leadership_message: 'A nossa força reside na nossa unidade e na nossa vontade de sobressair juntos.',
      role_president: 'Presidente & Fundadora',
      role_vp_operations: 'Vice-Presidente de Operações',
      role_finance: 'Diretor Financeiro',
      role_international: 'Relações Internacionais',
      role_youth: 'Desenvolvimento da Juventude',
      role_hr: 'Recursos Humanos',
      council_member: 'Membro do Conselho'
    },
    support: {
      badge: 'Investimento',
      title: 'Apoie a Nova Elite',
      description: 'A sua contribuição direta financia bolsas e infraestruturas de crescimento.',
      donation_title: 'Doação Pontual',
      donation_description: 'Apoio imediato para as nossas ações urgentes.',
      volunteer_title: 'Voluntariado Líder',
      volunteer_description: 'Envolva o seu tempo e as suas competências.',
      sponsor_title: 'Patrocínio Corporativo',
      sponsor_description: 'Associe a sua marca à excelência.',
      donate_title: 'Investir no Futuro',
      donate_description: 'Cada doação é um pilar para as nossas academias e programas de aceleração.',
      choose_amount: 'Montante do investimento ($)',
      tax_notice: 'Recibos oficiais para dedução fiscal disponíveis.',
      secure_payment: 'Transação segura via PayPal',
      financial_scaling: 'Apoio ao Crescimento Financeiro',
      contribution_center: 'Centro de Contribuição',
      initiate_contribution: 'Iniciar Minha Contribuição',
      impact_50: 'Equipamento para um estudante criativo',
      impact_100: 'Acesso a um módulo de Masterclass',
      impact_250: 'Apoio a uma startup local',
      impact_500: 'Bolsa de Excelência Completa'
    },
    get_involved: {
      badge: 'Impacto',
      title: 'Moldar o Futuro Connosco',
      description: 'Existem várias formas de contribuir para o prestígio da nossa comunidade.',
      donate_title: 'Apoio Financeiro',
      donate_description: 'Invista nos nossos futuros líderes e empreendedores.',
      volunteer_title: 'Partilha de Especialização',
      volunteer_description: 'Torne-se mentor ou voluntário nas nossas cimeiras.',
      membership_title: 'Tornar-se Membro',
      membership_description: 'Junte-se à rede profissional mais influente da diáspora.',
      choose_amount: 'Montante da doação',
      custom_amount: 'Outro montante',
      donation_message: 'Sua mensagem (opcional)',
      donation_message_placeholder: 'Diga-nos o que o inspira...',
      anbi_notice: 'A CENA é uma organização sem fins lucrativos reconhecida no Canadá.',
      other_ways: 'Outras maneiras de se envolver',
      impact_title: 'Seu Impacto Concreto',
      impact_25: 'Material pedagógico para um estudante',
      impact_50: 'Acesso a um workshop de liderança',
      impact_100: 'Financiamento parcial de um projeto inovador',
      impact_250: 'Bolsas de mentoria completa'
    },
    blog: {
      badge: 'Notícias',
      title: 'Perspetivas & Insights',
      description: 'Análise e testemunhos de sucesso lusófono no Canadá.',
      read_full: 'Ler análise completa',
      newsletter_title: 'Mantenha-se Informado',
      newsletter_description: 'Junte-se ao nosso círculo restrito para atualizações exclusivas sobre o nosso impacto global.',
      subscribe_button: 'Subscrever',
      read_entry: 'Ler Artigo',
      subscription_active: 'Assinatura Ativa',
      intel_distribution: 'Distribuição Especial de Informação',
      email_placeholder: 'SEU E-MAIL',
      article1_title: 'Lançamento da Incubadora CENA',
      article1_excerpt: 'Como transformamos a ambição em sucesso concreto para novos empreendedores.',
      article1_author: 'Liderança CENA',
      article1_category: 'Empreendedorismo',
      article2_title: 'Inteligência Coletiva em Ação',
      article2_excerpt: 'Recordando a nossa última noite de networking que gerou mais de 15 colaborações.',
      article2_author: 'Coordenador de Rede',
      article2_category: 'Networking',
      article3_title: 'Alianças Educativas 2025',
      article3_excerpt: 'Novas parcerias com instituições de prestígio para os nossos bolseiros.',
      article3_author: 'Círculo de Educação',
      article3_category: 'Educação'
    },
    gallery: {
      badge: 'Momentos',
      title: 'Celebrações & Sucesso',
      subtitle: 'Retrospectiva em imagens dos nossos últimos encontros de prestígio',
      view_all: 'Galeria Completa',
      explore_instruction: 'Arraste ou clique para explorar'
    },
    subject: {
      label: 'Assunto',
      placeholder: 'Selecionar um assunto',
      membership: 'Tornar-se membro',
      volunteer: 'Voluntariado',
      partnership: 'Parceria',
      sponsorship: 'Patrocínio',
      other: 'Outro'
    },
    footer: {
      contact_bureau: 'Contacto do Escritório',
      follow_us: 'Siga-nos',
      get_in_touch: 'Contacto & Acesso',
      our_location: 'Sede Social',
      location_text: '3181 Montée Saint-hubert, QC, Canada',
      phone: 'Telefone Office',
      email: 'Ligação Direta',
      about_cena: 'Missão Institucional',
      about_text: 'A CENA é a organização de referência para o sucesso angolano e lusófono no Canadá.',
      send_message: 'Ligação Estratégica',
      your_name: 'Nome completo',
      your_email: 'Endereço de e-mail',
      subject: 'Assunto do pedido',
      your_message: 'Sua mensagem ou proposta',
      send_message_btn: 'Transmitir o pedido',
      quick_links: 'Links Rápidos',
      legal: 'Avisos Legais',
      privacy_policy: 'Confidencialidade de dados',
      terms_of_service: 'Termos e Condições',
      description: 'Excelência, Ambição e Herança ao serviço de uma comunidade radiante.',
      copyright: '© 2025 CENA - Comunidade de Educação e Networking Angolana. Todos os direitos reservados.',
      built_with_love: 'Impulsionado pela inteligência coletiva.'
    }
  }
};