import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'fr' | 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('fr');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('cena-language') as Language;
    if (savedLanguage && ['fr', 'en', 'pt'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('cena-language', language);
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      value = value?.[k];
    }

    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const translations = {
  fr: {
    common: {
      donate_now: 'Faire un don',
      read_more: 'Lire plus',
      learn_more: 'En savoir plus',
      show_less: 'Voir Moins ↑',
      contact_us: 'Nous contacter',
      get_involved: 'S\'impliquer',
      view_all: 'Voir tout',
      sign_up: 'S\'inscrire',
      join_us: 'Rejoignez-nous',
      trusted_by: 'Ils nous font confiance'
    },
    navigation: {
      home: 'Accueil',
      about: 'À propos',
      mission: 'Mission',
      vision: 'Vision',
      programs: 'Programmes',
      partners: 'Partenaires',
      members: 'Membres',
      events: 'Événements',
      recent_events: 'Événements Récents',
      team: 'Équipe',
      support: 'Soutien',
      blog: 'Blog',
      contact: 'Contact',
      gallery: 'Galerie'
    },
    hero: {
      title: 'CENA | Communauté d\'Éducation et de Networking Angolaise.',
      subtitle: 'Organisme à but non lucratif',
      description: 'Autonomiser la diaspora angolaise et lusophone au Canada grâce à une éducation stratégique, l\'entrepreneuriat et un réseau d\'influence mondial.',
      cta_primary: 'Soutenez l\'Impact',
      cta_secondary: 'Nos Programmes',
      members_connected: 'Membres Connectés',
      active_programs: 'Programmes Actifs',
      partners: 'Partenaires Stratégiques',
      stat_members: '300+',
      stat_programs: '12',
      stat_partners: '20+'
    },
    about: {
      badge: 'L\'Essence de CENA',
      title: "Une Communauté d'Excellence & Impact",
      description: 'CENA incarne la force de la diaspora angolaise au Canada — une plateforme d\'excellence dédiée à l\'essor intellectuel et économique de notre héritage.',
      who_we_are: 'Qui nous sommes',
      who_we_are_text: 'Organisation d\'élite dédiée à l\'autonomisation de la diaspora lusophone par le mentorat, le leadership et l\'action collaborative de haut niveau.',
      our_approach: 'Notre Vision Stratégique',
      our_approach_text: 'Nous transformons l\'ambition en réalité grâce à un écosystème unique combinant éducation de pointe et synergie entrepreneuriale.',
      stats_title: 'Objectifs Stratégiques 2028',
      five_years_goals: "Nos Objectifs d'ici cinq ans",
      stats: {
        members: 'Membres Actifs',
        workshops: 'Ateliers Leaders',
        partnerships: 'Alliances Stratégiques',
        years: 'Excellence & Impact',
        badge_impact: 'Professionnalisme'
      }
    },
    mission: {
      badge: 'Notre Engagement',
      title: 'Bâtir un Héritage Durable',
      description: 'Notre mission transcende l\'entraide : nous créons les leaders de demain à travers un accompagnement sur mesure.',
      pillar1_title: 'Ingénierie de l\'Éducation',
      pillar1_desc: 'Accès à des ressources de calibre mondial pour le développement de l\'expertise et de la pensée innovante.',
      pillar2_title: 'Écosystème Entrepreneuriat',
      pillar2_desc: 'Catalyseur de succès pour les entreprises lusophones, du démarrage à l\'expansion internationale.',
      pillar3_title: 'Réseau d\'Influence',
      pillar3_desc: 'Connexions de haut niveau ouvrant les portes des marchés canadiens et internationaux.'
    },
    vision: {
      badge: 'Horizon 2030',
      title: 'Devenir le Pilier de la Diaspora',
      description: 'Nous aspirons à être la référence indiscutable pour l\'intégration et le succès des talents lusophones en Amérique du Nord.',
      goal1: 'Souveraineté Éducative',
      goal1_desc: 'Programmes certifiés d\'excellence favorisant une réussite académique et professionnelle sans précédent.',
      goal2: 'Leadership Économique',
      goal2_desc: 'Propulser la croissance durable à travers des fonds et des conseils stratégiques pour entrepreneurs.',
      goal3: 'Cohésion & Prestige',
      goal3_desc: 'Rayonnement de la culture angolaise à travers des succès concrets et une influence durable.',
      read_objective: 'Lire l\'Objectif'
    },
    programs: {
      badge: 'Écosystème CENA',
      title: 'Programmes de Transformation',
      description: 'Des piliers stratégiques conçus pour chaque étape de votre parcours : de l\'étudiant passionné au PDG influent.',
      academy_title: 'CENA Academy',
      academy_description: 'Masterclass et formations certifiantes pour l\'élite de demain.',
      academy_details: 'Un curriculum rigoureux couvrant la gestion, la technologie et les soft skills nécessaires pour exceller dans le marché canadien.',
      academy_impact: 'Éducation',
      women_title: 'Élite Féminine',
      women_description: 'Catalyseur de leadership pour les femmes influentes de la communauté.',
      women_details: 'Un espace dédié pour briser les plafonds de verre, favoriser le networking stratégique et le développement du leadership féminin.',
      women_impact: 'Leadership',
      youth_title: 'Génération Innovation',
      youth_description: 'Former les pionniers technologiques et créatifs de la diaspora.',
      youth_details: 'Programmes immersifs en codage, design et innovation pour préparer la jeunesse aux métiers du futur.',
      youth_impact: 'Innovation',
      mentorship_title: 'Cercle de Mentorat',
      mentorship_description: 'Apprendre des plus grands pour accélérer votre propre ascension.',
      mentorship_details: 'Mise en relation directe avec des cadres et entrepreneurs établis pour un transfert de connaissances et d\'expérience critique.',
      mentorship_impact: 'Mentorat',
      entrepreneurship_title: 'HUB Entrepreneur',
      entrepreneurship_description: 'Accélérateur de croissance et mentorat pour entreprises ambitieuses.',
      entrepreneurship_details: 'Accompagnement de A à Z : du business plan à la levée de fonds et au développement de marché.',
      entrepreneurship_impact: 'Affaires',
      integration_title: 'Intégration & Essor',
      integration_description: 'Parcours d\'accueil privilégié pour une insertion rapide et réussie.',
      integration_details: 'Support administratif, linguistique et culturel pour transformer l\'immigration en une transition fluide vers le succès.',
      integration_impact: 'Social',
      events_title: 'Sommets & Ateliers',
      events_description: 'Échanges de haut niveau et intelligence collective en action.',
      events_details: 'Organisation d\'événements d\'influence réunissant experts mondiaux et talents locaux.',
      events_impact: 'Networking',
      volunteer_title: 'Programme de Bénévolat',
      volunteer_description: 'Opportunités de contribuer et de faire une différence ensemble.',
      volunteer_details: 'Rejoignez notre réseau de leaders et d\'experts pour soutenir les initiatives de la diaspora angolaise au Canada.',
      volunteer_impact: 'Impact',
      join_program_title: 'Prêt à Recommander l\'Excellence?',
      join_program_description: 'Que vous soyez étudiant, entrepreneur ou expert, votre place est parmi nous.',
      join_program_button: 'Devenir Membre'
    },
    partners: {
      badge: 'Alliances',
      title: 'Construire l\'Avenir Ensemble',
      description: 'Nous collaborons avec des institutions de prestige pour démultiplier l\'impact de nos initiatives.',
      partner_type_corporate: 'Partenaires Corporatifs',
      partner_type_community: 'Organisations Communautaires',
      partner_type_educational: 'Institutions Éducatives',
      partner_type_government: 'Soutien Institutionnel',
      become_partner_title: 'Devenir Partenaire Stratégique',
      become_partner_desc: 'Joignez vos forces à CENA pour catalyser le succès de la diaspora lusophone au Canada.',
      become_partner_button: 'Initier un Partenariat'
    },
    members: {
      badge: 'Cercle CENA',
      title: 'Une Communauté d\'Élite',
      description: 'Ingénieurs, artistes, entrepreneurs et étudiants unis par la quête de l\'excellence.',
      benefit1: 'Accès exclusif au réseau de mentorat CENA.',
      benefit2: 'Tarifs préférentiels pour nos sommets annuels.',
      benefit3: 'Accès prioritaire à notre plateforme de recrutement.',
      benefit4: 'Invitations à des ateliers de leadership privés.',
      benefit5: 'Publication de vos succès dans notre newsletter.',
      benefit6: 'Soutien administratif pour l\'entrepreneuriat.',
      join_title: 'Rejoindre l\'Avant-Garde',
      join_desc: 'Unissez-vous à un réseau dynamique où chaque parcours individuel nourrit notre ambition collective.',
      join_button: 'Obtenir ma Carte de Membre'
    },
    events: {
      badge: 'Calendrier',
      title: 'Événements Stratégiques',
      description: 'Des rendez-vous exclusifs pour expandre votre réseau et vos connaissances.',
      upcoming: 'Sommets à Venir',
      register_now: 'Réserver ma place',
      type_workshop: 'Gala Exclusif',
      type_networking: 'Networking Élite',
      type_cultural: 'Célébration Prestige',
      event1_title: 'Gala des Entrepreneurs Lusophones',
      event1_description: 'Une célébration prestigieuse de l\'excellence et du leadership entrepreneurial au sein de la communauté lusophone.',
      event1_location: 'Montréal HQ',
      event2_title: 'Sommet des Leaders Diaspora',
      event2_description: 'Rencontre annuelle des entrepreneurs et influenceurs lusophones au Canada.',
      event2_location: 'BUREAU CENA',
      event3_title: 'Gala de l\'Excellence Culturelle Angolaise',
      event3_description: 'Une soirée de prestige célébrant nos réussites culturelles et économiques.',
      event3_location: 'Hôtel Hilton',
      coming_soon: 'À Déterminer',
      past_events: 'Héritage d\'Événements',
      past_event_success: 'Tous les sommets organisés avec un taux de satisfaction de 98%.',
      explore_calendar: 'Nous Contacter',
      register: 'S\'inscrire'
    },
    team: {
      badge: 'Gouvernance',
      title: 'Conseil d\'Administration',
      description: 'Une équipe visionnaire dédiée au rayonnement de la diaspora angolaise.',
      leadership_title: 'Vision de la Présidence',
      leadership_message: 'Notre force réside dans notre unité et notre volonté d\'exceller ensemble.',
      role_president: 'Présidente & Fondatrice',
      role_vp_operations: 'Vice-Présidente des Opérations',
      role_finance: 'Directeur Financier',
      role_international: 'Relations Internationales',
      role_youth: 'Développement de la Jeunesse',
      role_hr: 'Ressources Humaines',
      council_member: 'Membre du Conseil'
    },
    support: {
      badge: 'Investissement',
      title: 'Soutenez la Nouvelle Élite',
      description: 'Votre contribution directe finance les bourses et les infrastructures de croissance.',
      donation_title: 'Don Ponctuel',
      donation_description: 'Soutien immédiat pour nos actions urgentes.',
      volunteer_title: 'Bénévolat Leader',
      volunteer_description: 'Engagez votre temps et vos compétences.',
      sponsor_title: 'Sponsoring Corporatif',
      sponsor_description: 'Associez votre marque à l\'excellence.',
      donate_title: 'Investir dans le Futur',
      donate_description: 'Chaque don est un pilier pour nos académies et nos programmes d\'accélération.',
      choose_amount: 'Montant de l\'investissement ($)',
      tax_notice: 'Reçus officiels pour déduction fiscale disponibles.',
      secure_payment: 'Transaction sécurisée via PayPal',
      financial_scaling: 'Support à la Croissance Financière',
      contribution_center: 'Centre de Contribution',
      initiate_contribution: 'Initier ma Contribution',
      impact_50: 'Équipement pour un étudiant créatif',
      impact_100: 'Accès à un module de Masterclass',
      impact_250: 'Soutien à une startup locale',
      impact_500: 'Bourse d\'Excellence Completa'
    },
    get_involved: {
      badge: 'Impact',
      title: 'Façonnez l\'Avenir avec Nous',
      description: 'Il existe plusieurs façons de contribuer au rayonnement de notre communauté.',
      donate_title: 'Soutien Financier',
      donate_description: 'Investissez dans nos futurs leaders et entrepreneurs.',
      volunteer_title: 'Partage d\'Expertise',
      volunteer_description: 'Devenez mentor ou bénévole lors de nos sommets.',
      membership_title: 'Devenir Membre',
      membership_description: 'Rejoignez le réseau professionnel le plus influent de la diaspora.',
      choose_amount: 'Montant du don',
      custom_amount: 'Autre montant',
      donation_message: 'Votre message (optionnel)',
      donation_message_placeholder: 'Dites-nous ce qui vous inspire...',
      anbi_notice: 'CENA est un organisme à but non lucratif reconnu au Canada.',
      other_ways: 'Autres manières de s\'impliquer',
      impact_title: 'Votre Impact Concret',
      impact_25: 'Matériel pédagogique pour un étudiant',
      impact_50: 'Accès à un atelier de leadership',
      impact_100: 'Financement partiel d\'un projet innovant',
      impact_250: 'Bourse de mentorat complète'
    },
    blog: {
      badge: 'Perspectives',
      title: 'PERSPECTIVES & INSIGHTS',
      description: 'Décryptage et témoignages de la réussite lusophone au Canada.',
      read_full: 'Lire l\'analyse complète',
      newsletter_title: 'Restez Informé',
      newsletter_description: 'Rejoignez notre cercle restreint pour des mises à jour exclusives sur notre impact mondial.',
      subscribe_button: 'S\'abonner',
      read_entry: 'Lire l\'Article →',
      subscription_active: 'Abonnement Actif',
      intel_distribution: 'Distribution d\'Informations Privées',
      email_placeholder: 'VOTRE EMAIL',
      article1_title: "VOIX DU LEADERSHIP : Les Noirs qui font l'histoire",
      article1_subtitle: "Héritage d'Excellence — Sommet annuel",
      article1_excerpt: "Le sommet « Héritage d'Excellence » n'était pas seulement une célébration de la communauté ; il a servi de nexus puissant où l'initiative citoyenne a rencontré la reconnaissance institutionnelle de haut niveau. La présence et les hommages sincères de figures politiques clés ont souligné le rôle vital que les communautés noires et lusophones jouent dans le tissu social, économique et culturel du Canada. Cette convergence de leadership a mis en lumière un engagement partagé à bâtir une société où l'excellence est non seulement reconnue, mais activement nourrie par des alliances stratégiques.\n\nUn Salut de la Métropole et de la Région\nLa mairesse de Montréal, Soraya Martinez Ferrada, a mené les hommages en saluant le sommet comme un phare pour les précieuses contributions des communautés noires à l'identité de la ville. Son message a résonné avec une profonde appréciation pour la mission du CENA de créer des ponts pour la diaspora angolaise et lusophone, favorisant un environnement où la culture et l'innovation fleurissent. Ce sentiment a été partagé par Reine Bombo-Allara, conseillère municipale de Longueuil, qui a souligné le « génie » et les contributions fondamentales des citoyens noirs au dynamisme régional. À travers son regard, le CENA agit comme un vecteur critique de cohésion sociale et de dialogue interculturel permanent en Montérégie, forgeant des alliances durables qui profitent à l'ensemble du tissu social.\n\nPlaidoyer pour l'Intégrité et la Solidarité\nAux niveaux fédéral et provincial, les messages se sont tournés vers l'éthique du service et le pouvoir de la solidarité intergénérationnelle. Natilien Joseph, député de Longueuil—Saint-Hubert, a lancé un appel vibrant à l'action, exhortant la communauté à maintenir la « flamme de l'objectif original » et à servir avec intégrité. Son intervention a mis en relief la profonde responsabilité de la représentation civique dans l'amplification des voix des plus vulnérables. De même, Shirley Dorismond, députée de Marie-Victorin, a plaidé pour un leadership enraciné dans la solidarité, soulignant que le véritable progrès se mesure à la capacité de promouvoir une justice équitable. Elle a loué le CENA comme un pilier fondamental pour l'épanouissement des familles et le rayonnement régional de la diaspora.\n\nLe Pouvoir de l'Alliance Présidentielle\nAu cœur de ces dialogues institutionnels se trouvait la synergie visible entre Cristina Manuel, présidente du CENA, et ces figures influentes. Ces rencontres ont témoigné d'une vision commune dédiée à l'éducation et à l'entrepreneuriat. En combinant expertises et réseaux, ce leadership collectif ouvre de nouvelles voies vers l'excellence humaine et professionnelle, garantissant que l'héritage des bâtisseurs d'aujourd'hui continue d'inspirer les leaders de demain. Ce sommet a prouvé que lorsque le soutien institutionnel rencontre la passion communautaire, le résultat est une société radieuse et plus unie.",
      article1_author: 'Direction CENA',
      article1_category: 'Sommet',
      article1_date: '28 Février 2026',
      article2_title: 'MÊS DA CONSCIÊNCIA NEGRA | CENA & CAF',
      article2_subtitle: "Échos de l'Ancestralité — Identité angolaise",
      article2_excerpt: "Au cœur du Mois de la Conscience Noire, un événement d'une rare intensité a résonné dans les couloirs de la communauté lusophone de Montréal. La collaboration entre le CENA (Communauté Angolaise pour l'Éducation et le Networking) et le CAF (Centre d'Aide à la Famille) a donné naissance à une célébration qui a transcendé la simple commémoration pour devenir un véritable manifeste de culture, de mémoire et de résistance. Dans un espace baigné de couleurs vibrantes, les participants se sont réunis pour honorer un héritage qui traverse les océans et les générations, offert à travers une expérience immersive où chaque détail — des textiles soigneusement disposés aux arômes enveloppants des plats traditionnels — racontait une histoire d'appartenance profonde et de fierté.\n\nUn Musée Vivant de l'Identité\nLe lieu s'est transformé en un musée vivant de l'identité angolaise. Des tissus aux motifs géométriques complexes, tels que le célèbre samakaka et les capulanas florales, ornaient les murs, portant des codes sociaux et des histoires familiales préservées à travers les tempêtes de l'histoire. Au centre de l'exposition, un panneau cartographique des dix-huit provinces de l'Angola invitait les invités à un voyage intérieur à travers la richesse ethnolinguistique des peuples Bakongo, Ovimbundu et Tchokwe. Des artisans ont partagé un savoir-faire ancestral, du perlage à l'art du turban traditionnel, veillant à ce que les gestes des arrière-grands-parents soient transmis aux plus jeunes membres de la diaspora.\n\nLa Table comme Héritage Sacré\nLa gastronomie occupait une place centrale, fidèle à la tradition où la table est un lieu sacré de communion. Le buffet offrait un panorama de saveurs — de la muamba de galinha au symbolique funge de milho — servant de catalyseur pour le réseautage et les échanges. Au-delà du plaisir gustatif, ces moments ont favorisé le dialogue entre professionnels établis et étudiants nouvellement arrivés, prouvant qu'à la table de l'exil, la saveur de la patrie est le passeport le plus puissant.\n\nUn Héritage d'Excellence\nCette synergie entre le CENA et le CAF incarne un modèle de collaboration institutionnelle, jetant un pont entre le passé et l'avenir. La présence de familles entières attestait du succès intergénérationnel de cette célébration. Le Mois de la Conscience Noire, tel que célébré ici, n'était pas un exercice de nostalgie mais un acte de construction — renouvelant la solidarité et veillant à ce que l'excellence de la diaspora angolaise au Canada continue de briller avec la force de mille soleils.",
      article2_author: 'Rédaction CENA',
      article2_category: 'Culture',
      article2_date: '20 Février 2026',
      article3_title: 'INCUBATEUR CENA : ARCHITECTURER LE SUCCÈS LUSOPHONE',
      article3_subtitle: 'Propulser la Vision — Un Catalyseur Socio-Économique Stratégique',
      article3_excerpt: 'Le lancement de l\'Incubateur CENA représente bien plus que l\'introduction d\'un nouveau programme communautaire ; c\'est un bond stratégique profond vers l\'avenir de la diaspora lusophone au Canada. Pour de nombreux immigrants, le voyage vers l\'Amérique du Nord est porté par un talent brut et une expertise ancestrale.\n\nL\'Incubateur CENA arrive comme une solution définitive pour combler ce fossé critique. Notre mission est d\'identifier ces « talents invisibles » et de les transformer méticuleusement en entreprises évolutives, durables et hautement compétitives au sein du paysage canadien. En offrant un mentorat spécialisé, une littératie financière avancée et un écosystème de réseautage de haut niveau, nous veillons à ce que l\'artisan lusophone ne se contente pas de survivre, mais mène le marché.\n\nL\'impact de cet incubateur est une injection revitalisante directe dans l\'économie canadienne. En autonomisant les entrepreneurs lusophones, nous créons des emplois locaux et enrichissons le tissu commercial de hubs majeurs comme Montréal et Longueuil. Nous formons une génération de leaders qui transforment les « talents d\'origine » en « moteurs de prospérité », prouvant que la diversité culturelle est le moteur le plus efficace de l\'innovation moderne.',
      article3_author: 'Rédaction CENA',
      article3_category: 'Entrepreneuriat',
      article3_date: 'Janvier 2026',
      article4_title: 'Intelligence Collective en Action',
      article4_subtitle: 'La force du savoir partagé',
      article4_excerpt: 'L\'impact tangible de plus de 15 collaborations et la puissance des connaissances partagées.',
      article4_author: 'Iolanda Mendes (Impact/Networking focus)',
      article4_category: 'Networking',
      article4_date: 'Décembre 2025',
      article5_title: 'Alliances Éducatives 2025',
      article5_subtitle: 'Partenariats de prestige pour boursiers globaux',
      article5_excerpt: 'L\'impact futur des partenariats stratégiques pour nos étudiants et boursiers à l\'échelle mondiale.',
      article5_author: 'Dulce Angelina (Educational/Future-Legacy focus)'
    },
    gallery_page: {
      next_album: 'ALBUM SUIVANT',
      photo_credit: 'Photo par Randy Sélection 514-575-5019',
      breadcrumb_home: 'Accueil',
      breadcrumb_gallery: 'Galerie',
      albums: {
        consciousness: {
          title: 'MÊS DA CONSCIÊNCIA NEGRA\nCENA | CAF',
          subtitle: 'Célébration de l\'héritage et de la fierté en Montérégie',
          date: 'Février 2026',
          count: '13 moments capturés'
        },
        heritage: {
          title: 'HÉRITAGE D\'EXCELLENCE',
          subtitle: 'Les Noirs qui font l\'Histoire — Sommet annuel',
          date: '28 Février 2026',
          count: '116 moments capturés'
        }
      }
    },
    legal: {
      privacy_policy: "CONFIDENTIALITÉ",
      terms_of_use: "CONDITIONS",
      privacy_headline: "POLITIQUE DE CONFIDENTIALITÉ",
      privacy_compliance: "En conformité avec la Loi 25 du Québec et la LPRPDE du Canada",
      purpose_title: "Finalité de la collecte",
      purpose_text: "CENA (NEQ : 1181556193) collecte des renseignements personnels (nom, courriel et préférences) uniquement à des fins de réseautage communautaire, d'inscription à des événements et de sensibilisation éducative. Nous ne vendons pas vos données à des tiers.",
      consent_title: "Consentement explicite",
      consent_text: "En utilisant nos formulaires, vous donnez votre consentement explicite à CENA pour traiter vos informations. En vertu de la Loi 25, vous avez le droit de retirer ce consentement à tout moment.",
      retention_title: "Rétention des données",
      retention_text: "Nous ne conservons les renseignements personnels que le temps nécessaire à la réalisation des fins pour lesquelles ils ont été collectés ou tel que requis par la loi canadienne.",
      data_headline: "PROTECTION DES RENSEIGNEMENTS ET GOUVERNANCE",
      data_subheadline: "Notre engagement envers la sécurité et la conformité à la Loi 25",
      officer_title: "Le responsable de la protection de la vie privée",
      officer_text: "Comme l'exige la Loi 25, CENA a nommé un Responsable de la protection des renseignements personnels.",
      officer_contact: "Contact : info1@cena-ca.org",
      officer_role: "Rôle : Supervise la sécurité des données, traite les demandes d'accès et gère le « Registre des incidents de confidentialité ».",
      security_title: "Mesures de sécurité",
      security_text: "Nous mettons en œuvre des mesures de protection technologiques (cryptage et hébergement sécurisé) pour empêcher tout accès non autorisé. En cas de violation de données présentant un « risque de préjudice grave », nous en informerons immédiatement la Commission d'accès à l'information du Québec (CAI) et les utilisateurs concernés.",
      rights_title: "Vos droits (le « droit à l'oubli »)",
      rights_list: "Vous avez le droit à :",
      rights_portability: "Accès et portabilité : Recevoir vos données dans un format technologique structuré.",
      rights_deindexing: "Désindexation : Demander à CENA de cesser de diffuser vos renseignements personnels ou de les supprimer entièrement de nos dossiers numériques.",
      agree_terms: "J'accepte la politique de confidentialité et les conditions de protection des données."
    },
    terms: {
      headline: "CONDITIONS D'UTILISATION",
      subheadline: "Gouvernance et conditions de service de CENA",
      section1_title: "01. Acceptation des conditions",
      section1_text: "En accédant à ce site web, vous acceptez d'être lié par ces conditions d'utilisation et par toutes les lois et réglementations applicables au Canada et au Québec.",
      section2_title: "02. Licence d'utilisation",
      section2_text: "La permission est accordée de télécharger temporairement une copie des documents (informations ou logiciels) sur le site web de CENA pour un visionnement personnel et non commercial uniquement.",
      section3_title: "03. Gouvernance",
      section3_text: "Toute réclamation relative au site web de CENA sera régie par les lois de la province de Québec sans égard à ses dispositions en matière de conflit de lois.",
      footer_text: "Conditions d'utilisation © CENA 2026. Entité légale NEQ : 1181556193."
    },
    cookies: {
      title: "Gestion des Cookies",
      description: "Nous utilisons des cookies pour améliorer votre expérience. Conformément à la Loi 25, nous garantissons la protection de vos données et votre droit de choisir.",
      accept: "Accepter",
      decline: "Refuser"
    },
    gallery: {
      badge: 'COMMUNAUTÉ',
      title: 'NOËL SOLIDAIRE',
      subtitle: '"Transformer Noël en sourires et en espoir."',
      explore_instruction: 'Explorez la Galerie Architecturale'
    },
    featured_event: {
      badge: 'Événement Phare',
      title: 'JOURNÉE DE LA CONSCIENCE NOIRE',
      subtitle: 'Célébration de l\'héritage, de la fierté et de l\'excellence noire au Canada',
      date: '28 février 2026 — Longueuil',
      cta: 'Explorer la Galerie'
    },
    subject: {
      label: 'Objet',
      placeholder: 'Sélectionner un objet',
      membership: '01 CENA ACADEMY',
      volunteer: '06 PROGRAMME DE BÉNÉVOLAT',
      programs: '03 GÉNÉRATION INNOVATION',
      events: 'Événements',
      partnership: 'Partenariat',
      sponsorship: 'Sponsoring',
      other: 'Autre',
      elite_women: '02 ÉLITE FÉMININE',
      mentoring_circle: '04 CERCLE DE MENTORAT',
      entrepreneur_hub: '05 HUB ENTREPRENEUR'
    },
    footer: {
      contact_bureau: 'Contact Bureau',
      follow_us: 'Suivez-nous',
      get_in_touch: 'Contact & Accès',
      our_location: 'Siège Social',
      location_text: '3181 Montée Saint-hubert, QC, Canada',
      phone: 'Téléphone Office',
      email: 'Liaison Directe',
      about_cena: 'Mission Institutionnelle',
      about_text: 'CENA est l\'organisme de référence pour le rayonnement angolais et lusophone au Canada.',
      send_message: 'Liaison Stratégique',
      your_name: 'Nom complet',
      your_email: 'Adresse courriel',
      subject: 'Objet de la demande',
      your_message: 'Votre message ou proposition',
      send_message_btn: 'Transmettre la demande',
      quick_links: 'Navigation Rapide',
      legal: 'Mentions Légales',
      privacy_policy: 'Confidentialité des données',
      terms_of_service: 'Conditions générales',
      description: 'Communauté d\'Éducation et de Networking Angolaise.',
      copyright: "© 2026 CENA – Comunidade de Educação e Networking Angolana. Tous droits réservés.",
      built_with_love: "Powered by ProjectionAI"
    }
  },
  en: {
    common: {
      donate_now: 'Donate Now',
      read_more: 'Read More',
      learn_more: 'Learn More',
      show_less: 'Show Less ↑',
      contact_us: 'Contact Us',
      get_involved: 'Get Involved',
      view_all: 'View All',
      sign_up: 'Sign Up',
      join_us: 'Join Us',
      trusted_by: 'Trusted By'
    },
    navigation: {
      home: 'Home',
      about: 'About',
      mission: 'Mission',
      vision: 'Vision',
      programs: 'Programs',
      partners: 'Partners',
      members: 'Members',
      events: 'Events',
      recent_events: 'Recent Events',
      team: 'Team',
      support: 'Support',
      blog: 'Blog',
      contact: 'Contact',
      gallery: 'Gallery'
    },
    hero: {
      title: 'CENA | Angolan Education & Networking Community.',
      subtitle: 'Non profit Organization',
      description: 'Empowering the Angolan and Lusophone diaspora in Canada through strategic education, entrepreneurship, and a global influence network.',
      cta_primary: 'Support the Impact',
      cta_secondary: 'Our Programs',
      members_connected: 'Connected Members',
      active_programs: 'Active Programs',
      partners: 'Strategic Partners',
      stat_members: '300+',
      stat_programs: '12',
      stat_partners: '20+'
    },
    about: {
      badge: 'The Essence of CENA',
      title: 'A Community of Excellence & Impact',
      description: 'CENA embodies the power of the Angolan diaspora in Canada — a platform of excellence dedicated to the intellectual and economic rise of our heritage.',
      who_we_are: 'Who We Are',
      who_we_are_text: 'An elite organization dedicated to empowering the Lusophone diaspora through high-level mentoring, leadership, and collaborative action.',
      our_approach: 'Our Strategic View',
      our_approach_text: 'We transform ambition into reality through a unique ecosystem combining leading-edge education and entrepreneurial synergy.',
      stats_title: 'Strategic Goals 2028',
      five_years_goals: 'Our Goals for the Next Five Years',
      stats: {
        members: 'Active Members',
        workshops: 'Leader Workshops',
        partnerships: 'Strategic Alliances',
        years: 'Excellence & Impact',
        badge_impact: 'Professionalism'
      }
    },
    mission: {
      badge: 'Our Commitment',
      title: 'Building a Lasting Legacy',
      description: 'Our mission goes beyond mutual aid: we create the leaders of tomorrow through tailored support.',
      pillar1_title: 'Education Engineering',
      pillar1_desc: 'Access to world-class resources for developing expertise and innovative thinking.',
      pillar2_title: 'Entrepreneurship Ecosystem',
      pillar2_desc: 'Catalyst for Lusophone business success, from startup to international expansion.',
      pillar3_title: 'Influence Network',
      pillar3_desc: 'High-level connections opening doors to Canadian and international markets.'
    },
    vision: {
      badge: 'Horizon 2030',
      title: 'Becoming the Diaspora Pillar',
      description: 'We aspire to be the indisputable reference for the integration and success of Lusophone talents in North America.',
      goal1: 'Educational Sovereignty',
      goal1_desc: 'Certified programs of excellence fostering unprecedented academic and professional success.',
      goal2: 'Economic Leadership',
      goal2_desc: 'Propelling sustainable growth through strategic funds and advice for entrepreneurs.',
      goal3: 'Cohesion & Prestige',
      goal3_desc: 'Shining Angolan culture through concrete success and lasting influence.',
      read_objective: 'Read Objective'
    },
    programs: {
      badge: 'CENA Ecosystem',
      title: 'Transformation Programs',
      description: 'Strategic pillars designed for every step of your journey: from passionate student to influential CEO.',
      academy_title: 'CENA Academy',
      academy_description: 'Masterclasses and certifying training for tomorrow\'s elite.',
      academy_details: 'A rigorous curriculum covering management, technology, and soft skills needed to excel in the Canadian market.',
      academy_impact: 'Education',
      women_title: 'Elite Women',
      women_description: 'Leadership catalyst for the community\'s influential women.',
      women_details: 'A dedicated space to break glass ceilings, foster strategic networking, and female leadership development.',
      women_impact: 'Leadership',
      youth_title: 'Innovation Generation',
      youth_description: 'Training the technological and creative pioneers of the diaspora.',
      youth_details: 'Immersive programs in coding, design, and innovation to prepare youth for future careers.',
      youth_impact: 'Innovation',
      mentorship_title: 'Mentoring Circle',
      mentorship_description: 'Learn from the greatest to accelerate your own ascent.',
      mentorship_details: 'Direct connection with established executives and entrepreneurs for critical knowledge and experience transfer.',
      mentorship_impact: 'Mentorship',
      entrepreneurship_title: 'Entrepreneur HUB',
      entrepreneurship_description: 'Growth accelerator and mentoring for ambitious businesses.',
      entrepreneurship_details: 'End-to-end support: from business plans to fundraising and market development.',
      entrepreneurship_impact: 'Business',
      integration_title: 'Integration & Rise',
      integration_description: 'Privileged welcome path for quick and successful integration.',
      integration_details: 'Administrative, linguistic, and cultural support to turn immigration into a smooth transition to success.',
      integration_impact: 'Social',
      events_title: 'Summits & Workshops',
      events_description: 'High-level exchanges and collective intelligence in action.',
      events_details: 'Organizing influential events bringing together global experts and local talents.',
      events_impact: 'Networking',
      volunteer_title: 'Volunteer Program',
      volunteer_description: 'Opportunities to contribute and make a difference together.',
      volunteer_details: 'Join our network of leaders and experts to support Angolan diaspora initiatives in Canada.',
      volunteer_impact: 'Impact',
      join_program_title: 'Ready to Recommend Excellence?',
      join_program_description: 'Whether you are a student, entrepreneur, or expert, your place is with us.',
      join_program_button: 'Become a Member'
    },
    partners: {
      badge: 'Alliances',
      title: 'Building the Future Together',
      description: 'We collaborate with prestigious institutions to multiply the impact of our initiatives.',
      partner_type_corporate: 'Corporate Partners',
      partner_type_community: 'Community Organizations',
      partner_type_educational: 'Educational Institutions',
      partner_type_government: 'Institutional Support',
      become_partner_title: 'Become a Strategic Partner',
      become_partner_desc: 'Join forces with CENA to catalyze the success of the Lusophone diaspora in Canada.',
      become_partner_button: 'Initiate a Partnership'
    },
    members: {
      badge: 'CENA Circle',
      title: 'An Elite Community',
      description: 'Engineers, artists, entrepreneurs, and students united by the quest for excellence.',
      benefit1: 'Exclusive access to the CENA mentoring network.',
      benefit2: 'Preferential rates for our annual summits.',
      benefit3: 'Priority access to our recruitment platform.',
      benefit4: 'Invitations to private leadership workshops.',
      benefit5: 'Publication of your successes in our newsletter.',
      benefit6: 'Administrative support for entrepreneurship.',
      join_title: 'Join the Avant-Garde',
      join_desc: 'Unite with a dynamic network where each individual journey feeds our collective ambition.',
      join_button: 'Get My Member Card'
    },
    events: {
      badge: 'Schedule',
      title: 'Strategic Events',
      description: 'Exclusive appointments to expand your network and knowledge.',
      upcoming: 'Upcoming Summits',
      register_now: 'Book My Seat',
      type_workshop: 'Exclusive Gala',
      type_networking: 'Elite Networking',
      type_cultural: 'Prestige Celebration',
      event1_title: 'Lusophone Entrepreneurs Gala',
      event1_description: 'A prestigious celebration of excellence and entrepreneurial leadership within the Lusophone community.',
      event1_location: 'Montreal HQ',
      event2_title: 'Diaspora Leaders Summit',
      event2_description: 'Annual meeting of Lusophone entrepreneurs and influencers in Canada.',
      event2_location: 'CENA OFFICE',
      event3_title: 'Angolan Cultural Excellence Gala',
      event3_description: 'A prestigious evening celebrating our cultural and economic achievements.',
      event3_location: 'Hilton Hotel',
      coming_soon: 'TBA',
      past_events: 'Legacy of Events',
      past_event_success: 'All summits organized with a 98% satisfaction rate.',
      explore_calendar: 'Get In Touch',
      register: 'Register'
    },
    team: {
      badge: 'Governance',
      title: 'Board of Directors',
      description: 'A visionary team dedicated to the radiance of the Angolan diaspora.',
      leadership_title: 'President\'s Vision',
      leadership_message: 'Our strength lies in our unity and our will to excel together.',
      role_president: 'President & Founder',
      role_vp_operations: 'VP of Operations',
      role_finance: 'Financial Director',
      role_international: 'International Relations',
      role_youth: 'Youth Development',
      role_hr: 'Human Resources',
      council_member: 'Council Member'
    },
    support: {
      badge: 'Investment',
      title: 'Support the New Elite',
      description: 'Your direct contribution funds scholarships and growth infrastructure.',
      donation_title: 'One-time Donation',
      donation_description: 'Immediate support for our urgent actions.',
      volunteer_title: 'Leader Volunteering',
      volunteer_description: 'Engage your time and skills.',
      sponsor_title: 'Corporate Sponsoring',
      sponsor_description: 'Associate your brand with excellence.',
      donate_title: 'Invest in the Future',
      donate_description: 'Every donation is a pillar for our academies and acceleration programs.',
      choose_amount: 'Investment Amount ($)',
      tax_notice: 'Official tax receipts available.',
      secure_payment: 'Secure transition via PayPal',
      financial_scaling: 'Financial Growth Support',
      contribution_center: 'Contribution Center',
      initiate_contribution: 'Initiate My Contribution',
      impact_50: 'Equipment for a creative student',
      impact_100: 'Access to a Masterclass module',
      impact_250: 'Support for a local startup',
      impact_500: 'Full Excellence Scholarship'
    },
    get_involved: {
      badge: 'Impact',
      title: 'Shape the Future with Us',
      description: 'There are many ways to contribute to our community\'s influence.',
      donate_title: 'Financial Support',
      donate_description: 'Invest in our future leaders and entrepreneurs.',
      volunteer_title: 'Expertise Sharing',
      volunteer_description: 'Become a mentor or volunteer at our summits.',
      membership_title: 'Become a Member',
      membership_description: 'Join the most influential professional network of the diaspora.',
      choose_amount: 'Donation Amount',
      custom_amount: 'Other Amount',
      donation_message: 'Your Message (optional)',
      donation_message_placeholder: 'Tell us what inspires you...',
      anbi_notice: 'CENA is a recognized non-profit organization in Canada.',
      other_ways: 'Other Ways to Get Involved',
      impact_title: 'Your Concrete Impact',
      impact_25: 'Teaching material for one student',
      impact_50: 'Access to a leadership workshop',
      impact_100: 'Partial funding for an innovative project',
      impact_250: 'Full mentoring scholarship'
    },
    blog: {
      badge: 'Perspectives',
      title: 'PERSPECTIVES & INSIGHTS',
      description: 'Decrypting stories and testimonies of Lusophone success in Canada.',
      read_full: 'Read Full Analysis',
      newsletter_title: 'Stay Informed',
      newsletter_description: 'Join our inner circle for exclusive updates on our global impact.',
      subscribe_button: 'Subscribe',
      read_entry: 'Read Entry →',
      subscription_active: 'Subscription Active',
      intel_distribution: 'Private Intel Distribution',
      email_placeholder: 'ENTER EMAIL',
      article1_title: 'VOICES OF LEADERSHIP: Black People Making History',
      article1_subtitle: 'Heritage of Excellence — Annual Summit',
      article1_excerpt: "The \"Heritage of Excellence\" summit was not merely a celebration of community; it served as a powerful nexus where grassroots initiative met high-level institutional recognition. The presence and heartfelt tributes from key political figures underscored the vital role that the Black and Lusophone communities play in the social, economic, and cultural fabric of Canada. This convergence of leadership highlighted a shared commitment to building a society where excellence is not only recognized but actively nurtured through strategic alliances.\n\nA Salute from the Metropolis and the Region\nThe Mayor of Montreal, Soraya Martinez Ferrada, led the tributes by saluting the summit as a beacon for the precious contributions of Black communities to the city’s identity. Her message resonated with a deep appreciation for CENA’s mission to create bridges for the Angolan and Lusophone diaspora, fostering an environment where culture and innovation flourish. This sentiment was echoed by Reine Bombo-Allara, City Councilor for Longueuil, who emphasized the \"genius\" and fundamental contributions of Black citizens to regional dynamism. Through her lens, CENA acts as a critical vector for social cohesion and permanent intercultural dialogue in Montérégie, forging lasting alliances that benefit the entire social fabric.\n\nAdvocacy for Integrity and Solidarity\nFrom the federal and provincial levels, the messages turned toward the ethics of service and the power of intergenerational solidarity. Natilien Joseph, Member of Parliament for Longueuil—Saint-Hubert, delivered a vibrant call to action, urging the community to maintain the \"flame of original purpose\" and serve with integrity. His intervention highlighted the profound responsibility of civic representation in amplifying the voices of the most vulnerable. Similarly, Shirley Dorismond, MNA for Marie-Victorin, advocated for leadership rooted in solidarity, stressing that true progress is measured by the capacity to promote equitable justice. She lauded CENA as a fundamental pillar for the flourishing of families and the regional influence of the diaspora.\n\nThe Power of the Presidential Alliance\nCentral to these institutional dialogues was the visible synergy between Cristina Manuel, President of CENA, and these influential figures. These meetings bore witness to a common vision dedicated to education and entrepreneurship. By combining expertise and networks, this leadership collective is opening new paths toward human and professional excellence, ensuring that the legacy of today’s builders continues to inspire the leaders of tomorrow. This summit was a testament to the fact that when institutional support meets community passion, the result is a radiant, more united society.",
      article1_author: 'CENA Leadership',
      article1_category: 'Summit',
      article1_date: 'February 28, 2026',
      article2_title: 'BLACK CONSCIOUSNESS MONTH | CENA & CAF',
      article2_subtitle: 'Echoes of Ancestry — Angolan Identity',
      article2_excerpt: "At the heart of Black Consciousness Month, an event of rare intensity resonated through the corridors of the Lusophone community in Montréal. The collaboration between CENA (Angolan Community for Education and Networking) and CAF (Family Assistance Center) gave birth to a celebration that transcended simple commemoration, becoming a true manifesto of culture, memory, and resistance. In a space bathed in vibrant colors, participants gathered to honor a heritage that crosses oceans and generations, offered through an immersive experience where every detail—from the carefully arranged textiles to the enveloping aromas of traditional dishes—told a story of profound belonging and pride.\n\nA Living Museum of Identity\nThe venue was transformed into a living museum of Angolan identity. Fabrics with complex geometric patterns, such as the celebrated samakaka and floral capulanas, adorned the walls, carrying social codes and family histories preserved through the storms of history. At the center of the exhibition, a cartographic panel of Angola’s eighteen provinces invited guests on an inner journey through the ethnolinguistic richness of the Bakongo, Ovimbundu, and Tchokwe peoples. Artisans shared ancestral expertise, from beadwork to the art of the traditional turban, ensuring that the gestures of great-grandparents were passed down to the youngest members of the diaspora.\n\nThe Table as Sacred Heritage\nGastronomy occupied a central place, faithful to the tradition where the table is a sacred place of communion. The buffet offered a panorama of flavors—from muamba de galinha to the symbolic funge de milho—serving as a catalyst for networking and exchange. Beyond gustatory pleasure, these moments fostered dialogue between established professionals and newly arrived students, proving that at the table of exile, the flavor of the homeland is the most powerful passport.\n\nA Legacy of Excellence\nThis synergy between CENA and CAF embodies a model of institutional collaboration, bridging the gap between past and future. The presence of entire families attested to the intergenerational success of this celebration. Black Consciousness Month, as celebrated here, was not an exercise in nostalgia but an act of construction—renewing solidarity and ensuring that the excellence of the Angolan diaspora in Canada continues to shine with the force of a thousand suns.",
      article2_author: 'CENA Editorial',
      article2_category: 'Culture',
      article2_date: 'February 20, 2026',
      article3_title: 'CENA INCUBATOR: ARCHITECTING LUSOPHONE SUCCESS',
      article3_subtitle: 'Launching into Vision — A Strategic Socio-Economic Catalyst',
      article3_excerpt: 'The launch of the CENA Incubator represents far more than the introduction of a new community program; it is a profound strategic leap into the future of the Lusophone diaspora in Canada. For many immigrants, particularly those arriving from Angola and other Portuguese-speaking nations, the journey to North America is fueled by more than just aspirations—it is carried by raw, untapped talent and a deep well of ancestral expertise. From the precise, artisanal art of pastry and traditional gastronomy to the vibrant specialized retail of Afroshops, the meticulous skill of estheticians, and the soulful warmth of family-run restaurants, these entrepreneurs bring high-value vocations that are often underutilized or relegated to the informal economy due to a lack of structural support, local business literacy, and strategic networking.\n\nThe CENA Incubator arrives as a definitive solution to bridge this critical gap. Our mission is to identify these "invisible talents" and meticulously transform them into scalable, sustainable, and highly competitive businesses within the Canadian landscape. By providing specialized mentorship, advanced financial literacy, and a high-level networking ecosystem, we are ensuring that the Angolan baker, the creative stylist, or the tech-savvy artisan doesn’t just survive in the competitive marketplace but actively leads it. This initiative is a bold, public declaration that our community’s cultural heritage is not just a point of pride, but a formidable economic asset that deserves to be professionalized, scaled, and integrated into the global economy.\n\nThe ripple effect of this incubator extends far beyond our community borders; it is a direct, revitalizing injection into the Canadian economy. Small and medium-sized enterprises (SMEs) are the undisputed backbone of this nation’s prosperity. By empowering Lusophone entrepreneurs, we are creating local jobs, increasing regional tax revenue, and enriching the multicultural commercial fabric of major hubs like Montréal and Longueuil. We are fostering a new generation of leaders who turn "talents of origin" into "engines of prosperity," proving through action that cultural diversity is the most effective driver of modern innovation.\n\nLaunching into the future means recognizing that the socio-economic empowerment of the diaspora is the most effective way to build a fairer, more integrated, and vibrant society. The CENA Incubator is the launchpad for this new era—one where every craft, from the artisan’s kitchen to the corporate boardroom, is honored as a pillar of Canadian excellence and a testament to the unwavering resilience of our people. We are not just building businesses; we are architecting a legacy of sustainable success that will inspire generations to come.',
      article3_author: 'Redação CENA',
      article3_category: 'Entrepreneurship',
      article3_date: 'January 2026',
      article4_title: 'Collective Intelligence in Action',
      article4_subtitle: 'The strength of shared knowledge',
      article4_excerpt: 'The tangible impact of over 15 collaborations and the power of shared knowledge.',
      article4_author: 'Iolanda Mendes (Impact/Networking focus)',
      article4_category: 'Networking',
      article4_date: 'December 2025',
      article5_title: 'Educational Alliances 2025',
      article5_subtitle: 'Prestige partnerships for global scholars',
      article5_author: 'Dulce Angelina',
      article5_category: 'Education',
      article5_date: 'November 2025'
    },
    gallery_page: {
      next_album: 'NEXT ALBUM',
      photo_credit: 'Photo by Randy Selection 514-575-5019',
      breadcrumb_home: 'Home',
      breadcrumb_gallery: 'Gallery',
      albums: {
        consciousness: {
          title: 'MÊS DA CONSCIÊNCIA NEGRA\nCENA | CAF',
          subtitle: 'Celebrating heritage and pride in Montérégie',
          date: 'February 2026',
          count: '13 moments captured'
        },
        heritage: {
          title: 'HERITAGE OF EXCELLENCE',
          subtitle: 'Black People Making History — Annual Summit',
          date: 'February 28, 2026',
          count: '116 moments captured'
        }
      }
    },
    legal: {
      privacy_policy: "PRIVACY",
      terms_of_use: "TERMS",
      privacy_headline: "PRIVACY POLICY",
      privacy_compliance: "In accordance with Quebec Law 25 and Canada’s PIPEDA",
      purpose_title: "Purpose of Collection",
      purpose_text: "CENA (NEQ: 1181556193) collects personal information (name, email, and preferences) solely for community networking, event registration, and educational outreach. We do not sell your data to third parties.",
      consent_title: "Explicit Consent",
      consent_text: "By using our forms, you provide explicit consent for CENA to process your information. Under Law 25, you have the right to withdraw this consent at any time.",
      retention_title: "Data Retention",
      retention_text: "We retain personal information only as long as necessary to fulfill the purposes for which it was collected or as required by Canadian law.",
      data_headline: "INFORMATION PROTECTION & GOVERNANCE",
      data_subheadline: "Our commitment to Security and Law 25 Compliance",
      officer_title: "The Privacy Officer",
      officer_text: "As required by Law 25, CENA has appointed a Privacy Officer (Responsable de la protection des renseignements personnels).",
      officer_contact: "Contact: info1@cena-ca.org",
      officer_role: "Role: Oversees data security, handles access requests, and manages the \"Confidentiality Incident Register.\"",
      security_title: "Security Measures",
      security_text: "We implement technological safeguards (encryption and secure hosting) to prevent unauthorized access. In the event of a data breach presenting a \"risk of serious injury,\" we will notify the Commission d’accès à l’information du Québec (CAI) and affected users immediately.",
      rights_title: "Your Rights (The \"Right to be Forgotten\")",
      rights_list: "You have the right to:",
      rights_portability: "Access & Portability: Receive your data in a structured technological format.",
      rights_deindexing: "De-indexing: Request that CENA stops disseminating your personal information or deletes it entirely from our digital records.",
      agree_terms: "I agree to the Privacy Policy and Data Protection terms."
    },
    terms: {
      headline: "TERMS OF USE",
      subheadline: "CENA Governance & Terms of Service",
      section1_title: "01. Acceptance of Terms",
      section1_text: "By accessing this website, you agree to be bound by these Terms of Use and all applicable laws and regulations in Canada and Quebec.",
      section2_title: "02. Use License",
      section2_text: "Permission is granted to temporarily download one copy of the materials (information or software) on CENA's website for personal, non-commercial transitory viewing only.",
      section3_title: "03. Governance",
      section3_text: "Any claim relating to CENA's website shall be governed by the laws of the Province of Quebec without regard to its conflict of law provisions.",
      footer_text: "Terms of Use © CENA 2026. Legal entity NEQ: 1181556193."
    },
    cookies: {
      title: "Cookie Management",
      description: "We use cookies to enhance your experience. In accordance with Law 25, we ensure your data is protected and you have the right to choose.",
      accept: "Accept",
      decline: "Decline"
    },
    gallery: {
      badge: 'COMMUNITY',
      title: 'SOLIDARITY CHRISTMAS',
      subtitle: '"Transforming Christmas into smiles and hope."',
      explore_instruction: 'Explore the Architectural Gallery'
    },
    featured_event: {
      badge: 'Featured Event',
      title: 'BLACK CONSCIOUSNESS DAY',
      subtitle: 'Celebrating heritage, pride and Black excellence in Canada',
      date: 'February 28, 2026 — Longueuil',
      cta: 'Explore the Gallery'
    },
    subject: {
      label: 'Subject',
      placeholder: 'Select a subject',
      membership: '01 CENA ACADEMY',
      volunteer: '06 VOLUNTEER PROGRAM',
      programs: '03 INNOVATION GENERATION',
      events: 'Events',
      partnership: 'Partnership',
      sponsorship: 'Sponsoring',
      other: 'Other',
      elite_women: '02 ELITE WOMEN',
      mentoring_circle: '04 MENTORING CIRCLE',
      entrepreneur_hub: '05 ENTREPRENEUR HUB'
    },
    footer: {
      contact_bureau: 'Office Contact',
      follow_us: 'Follow Us',
      get_in_touch: 'Contact & Access',
      our_location: 'Headquarters',
      location_text: '3181 Montée Saint-hubert, QC, Canada',
      phone: 'Office Phone',
      email: 'Direct Liaison',
      about_cena: 'Institutional Mission',
      about_text: 'CENA is the reference for the Angolan and Lusophone radiance in Canada.',
      send_message: 'Strategic Liaison',
      your_name: 'Full Name',
      your_email: 'Email Address',
      subject: 'Subject of Request',
      your_message: 'Your Message or Proposal',
      send_message_btn: 'Transmit Request',
      quick_links: 'Quick Links',
      legal: 'Legal Notice',
      privacy_policy: 'Data Privacy',
      terms_of_service: 'Terms & Conditions',
      description: 'Angolan Education and Networking Community.',
      copyright: "© 2026 CENA – Comunidade de Educação e Networking Angolana. All rights reserved.",
      built_with_love: "Powered by ProjectionAI"
    }
  },
  pt: {
    common: {
      donate_now: 'Doar Agora',
      read_more: 'Ler Mais',
      learn_more: 'Saber Mais',
      show_less: 'Ver Menos ↑',
      contact_us: 'Contacte-nos',
      get_involved: 'Participar',
      view_all: 'Ver Tudo',
      sign_up: 'Inscrever-se',
      join_us: 'Junte-se a Nós',
      trusted_by: 'Eles Confiam em Nós'
    },
    navigation: {
      home: 'Início',
      about: 'Sobre',
      mission: 'Missão',
      vision: 'Visão',
      programs: 'Programas',
      partners: 'Parceiros',
      members: 'Membros',
      events: 'Eventos',
      recent_events: 'Eventos Recentes',
      team: 'Equipa',
      support: 'Apoio',
      blog: 'Blog',
      contact: 'Contacto',
      gallery: 'Galeria'
    },
    hero: {
      title: 'CENA | Comunidade de Educação e Networking Angolana.',
      subtitle: 'Organização sem fins lucrativos',
      description: 'Capacitando a diáspora angolana e lusófona no Canadá através de educação estratégica, empreendedorismo e uma rede de influência global.',
      cta_primary: 'Apoie o Impacto',
      cta_secondary: 'Nossos Programas',
      members_connected: 'Membros Conectados',
      active_programs: 'Programas Ativos',
      partners: 'Parceiros Estratégicos',
      stat_members: '300+',
      stat_programs: '12',
      stat_partners: '20+'
    },
    about: {
      badge: 'A Essência da CENA',
      title: 'Uma Comunidade de Excelência & Impacto',
      description: 'A CENA encarna a força da diáspora angolana no Canadá — uma plataforma de excelência dedicada ao desenvolvimento intelectual e económico da nossa herança.',
      who_we_are: 'Quem Somos',
      who_we_are_text: 'Organização de elite dedicada ao empoderamento da diáspora lusófona através de mentoria, liderança e ação colaborativa de alto nível.',
      our_approach: 'Visto Estratégica',
      our_approach_text: 'Transformamos ambição em realidade através de um ecossistema único que combina educação de ponta e sinergia empreendedora.',
      stats_title: 'Metas Estratégicas 2028',
      five_years_goals: 'Nossos Objetivos para os Próximos Cinco Anos',
      stats: {
        members: 'Membros Ativos',
        workshops: 'Workshops Líderes',
        partnerships: 'Alianças Estratégicas',
        years: 'Excelência & Impacto',
        badge_impact: 'Profissionalismo'
      }
    },
    mission: {
      badge: 'Nosso Compromisso',
      title: 'Construindo um Legado Duradouro',
      description: 'A nossa missão transcende a ajuda mútua: criamos os líderes de amanhã através de um acompanhamento personalizado.',
      pillar1_title: 'Engenharia da Educação',
      pillar1_desc: 'Acesso a recursos de classe mundial para o desenvolvimento de perícia e pensamento inovador.',
      pillar2_title: 'Ecossistema de Empreendedorismo',
      pillar2_desc: 'Catalisador de sucesso para empresas lusófonas, desde o arranque à expansão internacional.',
      pillar3_title: 'Rede de Influência',
      pillar3_desc: 'Conexões de alto nível que abrem as portas dos mercados canadianos e internacionais.'
    },
    vision: {
      badge: 'Horizonte 2030',
      title: 'Tornar-se o Pilar da Diáspora',
      description: 'Aspiramos a ser a referência indiscutível para a integração e o sucesso dos talentos lusófonos na América do Norte.',
      goal1: 'Soberania Educativa',
      goal1_desc: 'Programas certificados de excelência que promovem um sucesso académico e profissional sem precedentes.',
      goal2: 'Liderança Económica',
      goal2_desc: 'Propulsionar o crescimento sustentável através de fundos estratégicos e aconselhamento para empreendedores.',
      goal3: 'Coesão & Prestígio',
      goal3_desc: 'Divulgação da cultura angolana através de sucessos concretos e uma influência duradoura.',
      read_objective: 'Ler Objetivo'
    },
    programs: {
      badge: 'Ecossistema CENA',
      title: 'Programmes de Transformação',
      description: 'Pilares estratégicos concebidos para cada etapa do seu percurso: do estudante apaixonado ao CEO influente.',
      academy_title: 'Académie CENA',
      academy_description: 'Masterclasses e formações certificadas para a elite de amanhã.',
      academy_details: 'Um currículo rigoroso cobrindo gestão, tecnologia e soft skills necessárias para se destacar no mercado canadense.',
      academy_impact: 'Educação',
      women_title: 'Elite Feminina',
      women_description: 'Catalisador de liderança para as mulheres influentes da comunidade.',
      women_details: 'Um espaço dedicado para quebrar tetos de vidro, promover networking estratégico e o desenvolvimento da liderança feminina.',
      women_impact: 'Liderança',
      youth_title: 'Geração Inovação',
      youth_description: 'Formar os pioneiros tecnológicos e créatifs da diáspora.',
      youth_details: 'Programmas imersivos em codificação, design e inovação para preparar os jovens para as profissões do futuro.',
      youth_impact: 'Inovação',
      mentorship_title: 'Círculo de Mentoria',
      mentorship_description: 'Aprender com os melhores para acelerar a sua própria ascensão.',
      mentorship_details: 'Conexão direta com executivos e empresários estabelecidos para uma transferência crítica de conhecimento e experiência.',
      mentorship_impact: 'Mentoria',
      entrepreneurship_title: 'HUB Empreendedor',
      entrepreneurship_description: 'Acelerador de crescimento e mentoria para empresas ambiciosas.',
      entrepreneurship_details: 'Acompanhamento ponta a ponta: do plano de negócios à captação de recursos e desenvolvimento de mercado.',
      entrepreneurship_impact: 'Negócios',
      integration_title: 'Integração & Ascensão',
      integration_description: 'Percurso de acolhimento privilegiado para uma inserção rápida e bem-sucedida.',
      integration_details: 'Apoio administrativo, linguístico e cultural para transformar a imigração em uma transição suave para o sucesso.',
      integration_impact: 'Social',
      events_title: 'Cimeiras & Workshops',
      events_description: 'Intercâmbios de alto nível e inteligência coletiva em ação.',
      events_details: 'Organização de eventos influentes reunindo especialistas globais e talentos locais.',
      events_impact: 'Networking',
      volunteer_title: 'Programa de Voluntariado',
      volunteer_description: 'Oportunidades para contribuir e fazer a diferença juntos.',
      volunteer_details: 'Junte-se à nossa rede de líderes e especialistas para apoiar as iniciativas da diáspora angolana no Canadá.',
      volunteer_impact: 'Impacto',
      join_program_title: 'Pronto para Recomendar Excelência?',
      join_program_description: 'Quer seja estudante, empreendedor ou especialista, o seu lugar é connosco.',
      join_program_button: 'Torne-se Membro'
    },
    partners: {
      badge: 'Alianças',
      title: 'Construindo o Futuro Juntos',
      description: 'Colaboramos com instituições de prestígio para multiplicar o impacto das nossas iniciativas.',
      partner_type_corporate: 'Parceiros Corporativos',
      partner_type_community: 'Organizações Comunitárias',
      partner_type_educational: 'Instituições Educativas',
      partner_type_government: 'Apoio Institucional',
      become_partner_title: 'Tornar-se Parceiro Estratégico',
      become_partner_desc: 'Junte forças com a CENA para catalisar o sucesso da diáspora lusófona no Canadá.',
      become_partner_button: 'Iniciar Parceria'
    },
    members: {
      badge: 'Círculo CENA',
      title: 'Uma Comunidade de Elite',
      description: 'Engenheiros, artistas, empreendedores e estudantes unidos pela busca da excelência.',
      benefit1: 'Acesso exclusivo à rede de mentoria CENA.',
      benefit2: 'Taxas preferenciais para as nossas cimeiras anuais.',
      benefit3: 'Acesso prioritário à nossa plataforma de recrutamento.',
      benefit4: 'Convites para workshops de liderança privados.',
      benefit5: 'Publicação dos seus sucessos na nossa newsletter.',
      benefit6: 'Apoio administrativo para o empreendedorismo.',
      join_title: 'Junte-se à Vanguarda',
      join_desc: 'Una-se a uma rede dinâmica onde cada percurso individual alimenta a nossa ambição coletiva.',
      join_button: 'Obter o Meu Cartão de Membro'
    },
    events: {
      badge: 'Calendário',
      title: 'Eventos Estratégicos',
      description: 'Encontros exclusivos para expandir a sua rede e os seus conhecimentos.',
      upcoming: 'Próximas Cimeiras',
      register_now: 'Reservar o meu lugar',
      type_workshop: 'Gala Exclusivo',
      type_networking: 'Networking de Elite',
      type_cultural: 'Celebração de Prestígio',
      event1_title: 'Gala dos Empreendedores Lusófonos',
      event1_description: 'Uma celebração de prestígio da excelência e da liderança empreendedora na comunidade lusófona.',
      event1_location: 'Sede Montreal',
      event2_title: 'Cimeira de Líderes da Diáspora',
      event2_description: 'Encontro anual de empreendedores e influenciadores lusófonos no Canadá.',
      event2_location: 'ESCRITÓRIO CENA',
      event3_title: 'Gala da Excelência Cultural Angolana',
      event3_description: 'Uma noite de prestígio celebrando as nossas conquistas culturais e económicas.',
      event3_location: 'Hotel Hilton',
      coming_soon: 'A Definir',
      past_events: 'Legado de Eventos',
      past_event_success: 'Todas as cimeiras organizadas com uma taxa de satisfação de 98%.',
      explore_calendar: 'Solicitar Informações',
      register: 'Inscrever-se'
    },
    team: {
      badge: 'Governança',
      title: 'Conselho de Administração',
      description: 'Uma equipa visionária dedicada ao prestígio da diáspora angolana.',
      leadership_title: 'Visão da Presidência',
      leadership_message: 'A nossa força reside na nossa unidade e na nossa vontade de sobressair juntos.',
      role_president: 'Presidente & Fundadora',
      role_vp_operations: 'Vice-Presidente de Operações',
      role_finance: 'Diretor Financeiro',
      role_international: 'Relações Internacionais',
      role_youth: 'Desenvolvimento da Juventude',
      role_hr: 'Recursos Humanos',
      council_member: 'Membro do Conselho'
    },
    support: {
      badge: 'Investimento',
      title: 'Apoie a Nova Elite',
      description: 'A sua contribuição direta financia bolsas e infraestruturas de crescimento.',
      donation_title: 'Doação Pontual',
      donation_description: 'Apoio imediato para as nossas ações urgentes.',
      volunteer_title: 'Voluntariado Líder',
      volunteer_description: 'Envolva o seu tempo e as suas competências.',
      sponsor_title: 'Patrocínio Corporativo',
      sponsor_description: 'Associe a sua marca à excelência.',
      donate_title: 'Investir no Futuro',
      donate_description: 'Cada doação é um pilar para as nossas academias e programas de aceleração.',
      choose_amount: 'Montante do investimento ($)',
      tax_notice: 'Recibos oficiais para dedução fiscal disponíveis.',
      secure_payment: 'Transação segura via PayPal',
      financial_scaling: 'Apoio ao Crescimento Financeiro',
      contribution_center: 'Centro de Contribuição',
      initiate_contribution: 'Iniciar Minha Contribuição',
      impact_50: 'Equipamento para um estudante criativo',
      impact_100: 'Acesso a um módulo de Masterclass',
      impact_250: 'Apoio a uma startup local',
      impact_500: 'Bolsa de Excelência Completa'
    },
    get_involved: {
      badge: 'Impacto',
      title: 'Moldar o Futuro Connosco',
      description: 'Existem várias formas de contribuir para o prestígio da nossa comunidade.',
      donate_title: 'Apoio Financeiro',
      donate_description: 'Invista nos nossos futuros líderes e empreendedores.',
      volunteer_title: 'Partilha de Especialização',
      volunteer_description: 'Torne-se mentor ou voluntário nas nossas cimeiras.',
      membership_title: 'Tornar-se Membro',
      membership_description: 'Junte-se à rede profissional mais influente da diáspora.',
      choose_amount: 'Montante da doação',
      custom_amount: 'Outro montante',
      donation_message: 'Sua mensagem (opcional)',
      donation_message_placeholder: 'Diga-nos o que o inspira...',
      anbi_notice: 'A CENA é uma organização sem fins lucrativos reconhecida no Canadá.',
      other_ways: 'Outras maneiras de se envolver',
      impact_title: 'Seu Impacto Concreto',
      impact_25: 'Material pedagógico para um estudante',
      impact_50: 'Acesso a um workshop de liderança',
      impact_100: 'Financiamento parcial de um projeto inovador',
      impact_250: 'Bolsas de mentoria completa'
    },
    blog: {
      badge: 'Perspetivas',
      title: 'PERSPETIVAS & INSIGHTS',
      description: 'Análise e testemunhos de sucesso lusófono no Canadá.',
      read_full: 'Ler análise completa',
      newsletter_title: 'Mantenha-se Informado',
      newsletter_description: 'Junte-se ao nosso círculo restrito para atualizações exclusivas sobre o nosso impacto global.',
      subscribe_button: 'Subscrever',
      read_entry: 'Ler Artigo →',
      subscription_active: 'Assinatura Ativa',
      intel_distribution: 'Distribuição Especial de Informação',
      email_placeholder: 'SEU E-MAIL',
      article1_title: 'VOZES DE LIDERANÇA: Os Negros que fazem História',
      article1_subtitle: 'Herança de Excelência — Cimeira anual',
      article1_excerpt: 'A cimeira "Herança de Excelência" não foi apenas uma celebração da comunidade; serviu como um nexo poderoso onde a iniciativa de base se encontrou com o reconhecimento institucional de alto nível. A presença e os tributos sinceros de figuras políticas fundamentais sublinharam o papel vital que as comunidades negra e lusófona desempenham no tecido social, económico e cultural do Canadá. Esta convergência de liderança destacou um compromisso partilhado em construir uma sociedade onde a excelência não é apenas reconhecida, mas ativamente cultivada através de alianças estratégicas.\n\nUma Saudação da Metrópole e da Região\nA presidente da Câmara de Montreal, Soraya Martinez Ferrada, liderou os tributos saudando a cimeira como um farol para as preciosas contribuições das comunidades negras para a identidade da cidade. A sua mensagem ressoou com um profundo apreço pela missão da CENA de criar pontes para a diáspora angolana e lusófona, promovendo um ambiente onde a cultura e a inovação florescem. Este sentimento foi ecoado por Reine Bombo-Allara, vereadora de Longueuil, que enfatizou o "génio" e as contribuições fundamentais dos cidadãos negros para o dinamismo regional. Através da sua lente, a CENA atua como um vetor crítico para a coesão social e o diálogo intercultural permanente na Montérégie, forjando alianças duradouras que beneficiam todo o tecido social.\n\nAdvocacia pela Integridade e Solidariedade\nAos níveis federal e provincial, as mensagens voltaram-se para a ética do serviço e o poder da solidariedade intergeracional. Natilien Joseph, Deputado de Longueuil—Saint-Hubert, entregou um vibrante apelo à ação, instando a comunidade a manter a "chama do propósito original" e a servir com integridade. A sua intervenção destacou a profunda responsabilidade da representação cívica na amplificação das vozes dos mais vulneráveis. Da mesma forma, Shirley Dorismond, Deputada da Assembleia Nacional por Marie-Victorin, defendeu uma liderança enraizada na solidariedade, salientando que o verdadeiro progresso é medido pela capacidade de promover uma justiça equitativa. Ela elogiou a CENA como um pilar fundamental para o florescimento das famílias e a influência regional da diáspora.\n\nO Poder da Aliança Presidencial\nCentral a estes diálogos institucionais foi a sinergia visível entre Cristina Manuel, Presidente da CENA, e estas figuras influentes. Estas reuniões testemunharam uma visão comum dedicada à educação e ao empreendedorismo. Ao combinar especialização e redes, esta liderança coletiva está a abrir novos caminhos para a excelência humana e profissional, garantindo que o legado dos construtores de hoje continue a inspirar os líderes de amanhã. Esta cimeira foi um testemunho do facto de que quando o apoio institucional encontra a paixão da comunidade, o resultado é uma sociedade radiante e mais unida.',
      article1_author: 'Direção CENA',
      article1_category: 'Cimeira',
      article1_date: '28 de Fevereiro 2026',
      article2_title: 'MÊS DA CONSCIÊNCIA NEGRA | CENA & CAF',
      article2_subtitle: 'Ecos da Ancestralidade — Identidade angolana',
      article2_excerpt: 'No âmago do Mês da Consciência Negra, um evento de rara intensidade ressoou pelos corredores da comunidade lusófona em Montreal. A colaboração entre o CENA (Comunidade Angolana para Educação e Networking) e o CAF (Centro de Apoio à Família) deu origem a uma celebração que transcendeu a simples comemoração, tornando-se um verdadeiro manifesto de cultura, memória e resistência. Num espaço banhado por cores vibrantes, os participantes reuniram-se para honrar uma herança que atravessa oceanos e gerações, oferecida através de uma experiência imersiva onde cada detalhe — desde os têxteis cuidadosamente dispostos aos aromas envolventes dos pratos tradicionais — contava uma história de profunda pertença e orgulho.\n\nUm Museu Vivo da Identidade\nO local foi transformado num museu vivo da identidade angolana. Tecidos com padrões geométricos complexos, como a célebre samakaka e as capulanas florais, adornavam as paredes, carregando códigos sociais e histórias familiares preservadas através das tempestades da história. No centro da exposição, um painel cartográfico das dezoito províncias de Angola convidava os hóspedes a uma jornada interior pela riqueza etnolinguística dos povos Bakongo, Ovimbundu e Tchokwe. Artesãos partilharam conhecimentos ancestrais, do trabalho com missangas à arte do turbante tradicional, garantindo que os gestos dos bisavós fossem transmitidos aos membros mais jovens da diáspora.\n\nA Mesa como Herança Sagrada\nA gastronomia ocupou um lugar central, fiel à tradição onde a mesa é um lugar sagrado de comunhão. O buffet ofereceu um panorama de sabores — desde a muamba de galinha ao simbólico funge de milho — servindo como catalisador para o networking e a partilha. Além do prazer gustativo, estes momentos fomentaram o diálogo entre profissionais estabelecidos e estudantes recém-chegados, provando que na mesa do exílio, o sabor da pátria é o passaporte mais poderoso.\n\nUm Legado de Excelência\nEsta sinergia entre o CENA e o CAF encarna um modelo de colaboração institucional, lançando uma ponte entre o passado e o futuro. A presença de famílias inteiras atestou o sucesso geracional desta celebração. O Mês da Consciência Negra, como celebrado aqui, não foi um exercício de nostalgia, mas um ato de construção — renovando a solidariedade e garantindo que a excelência da diáspora angolana no Canadá continue a brilhar com a força de mil sóis.',
      article2_author: 'Redação CENA',
      article2_category: 'Cultura',
      article2_date: '20 de Fevereiro 2026',
      article3_title: 'INCUBADORA CENA: ARQUITETANDO O SUCESSO LUSÓFONO',
      article3_subtitle: 'Lançamento com Visão — Um Catalisador Socioeconómico Estratégico',
      article3_excerpt: 'O lançamento da Incubadora CENA representa muito mais do que a introdução de um novo programa comunitário; é um salto estratégico profundo para o futuro da diáspora lusófona no Canadá. Para muitos imigrantes, a viagem para a América do Norte é alimentada por mais do que apenas aspirações — é carregada por talento puro e uma perícia ancestral profunda.\n\nA Incubadora CENA chega como uma solução definitiva para colmatar esta lacuna crítica. A nossa missão é identificar estes "talentos invisíveis" e transformá-los meticulosamente em negócios escaláveis, sustentáveis e altamente competitivos no cenário canadiano. Ao fornecer mentoria especializada, literacia financeira avançada e um ecossistema de networking de alto nível, estamos a garantir que o artesão lusófono não apenas sobreviva, mas lidere ativamente o mercado. Esta iniciativa é uma declaração ousada e pública de que a herança cultural da nossa comunidade não é apenas um ponto de orgulho, mas um ativo económico formidável.\n\nO impacto desta incubadora estende-se muito além das fronteiras da nossa comunidade; é uma injeção revitalizante direta na economia canadiana. Ao capacitar os empreendedores lusófonos, estamos a criar empregos locais e a enriquecer o tecido comercial multicultural de grandes centros como Montreal e Longueuil. Estamos a fomentar uma nova geração de líderes que transformam "talentos de origem" em "motores de prosperidade", provando que a diversidade cultural é o motor mais eficaz da inovação moderna.',
      article3_author: 'Redação CENA',
      article3_category: 'Empreendedorismo',
      article3_date: 'Janeiro 2026',
      article4_title: 'Inteligência Coletiva em Ação',
      article4_subtitle: 'A força do conhecimento compartilhado',
      article4_excerpt: 'O impacto tangível de mais de 15 colaborações e o poder do conhecimento compartilhado.',
      article4_author: 'Iolanda Mendes (Impact/Networking focus)',
      article4_category: 'Networking',
      article4_date: 'Dezembro 2025',
      article5_title: 'Alianças Educativas 2025',
      article5_subtitle: 'Parcerias de prestígio para bolseiros globais',
      article5_excerpt: 'O impacto futuro de parcerias estratégicas para os nossos estudantes e bolseiros em todo o mundo.',
      article5_author: 'Dulce Angelina (Educational/Future-Legacy focus)',
      article5_category: 'Educação',
      article5_date: 'Novembro 2025'
    },
    gallery_page: {
      next_album: 'PRÓXIMO ÁLBUM',
      photo_credit: 'Foto por Randy Sélection 514-575-5019',
      breadcrumb_home: 'Início',
      breadcrumb_gallery: 'Galeria',
      albums: {
        consciousness: {
          title: 'MÊS DA CONSCIÊNCIA NEGRA\nCENA | CAF',
          subtitle: 'Celebrando a herança e o orgulho na Montérégie',
          date: 'Fevereiro 2026',
          count: '13 momentos capturados'
        },
        heritage: {
          title: 'HERANÇA DE EXCELÊNCIA',
          subtitle: 'Os Negros que fazem História — Cimeira anual',
          date: '28 de Fevereiro 2026',
          count: '116 momentos capturados'
        }
      }
    },
    legal: {
      privacy_policy: "PRIVACIDADE",
      terms_of_use: "TERMOS",
      privacy_headline: "POLÍTICA DE PRIVACIDADE",
      privacy_compliance: "Em conformidade com a Lei 25 do Quebec e a PIPEDA do Canadá",
      purpose_title: "Finalidade da Recolha",
      purpose_text: "CENA (NEQ: 1181556193) recolhe informações pessoais (nome, e-mail e preferências) exclusivamente para networking comunitário, registo em eventos e sensibilização educativa. Não vendemos os seus dados a terceiros.",
      consent_title: "Consentimento Explícito",
      consent_text: "Ao utilizar os nossos formulários, fornece consentimento explícito para a CENA processar as suas informações. Sob a Lei 25, tem o direito de retirar este consentimento a qualquer momento.",
      retention_title: "Retenção de Dados",
      retention_text: "Retemos informações pessoais apenas enquanto for necessário para cumprir os fins para os quais foram recolhidas ou conforme exigido pela lei canadiana.",
      data_headline: "PROTECÇÃO DE INFORMAÇÃO E GOVERNAÇÃO",
      data_subheadline: "Nosso compromisso com a Segurança e Conformidade com a Lei 25",
      officer_title: "O Responsável pela Privacidade",
      officer_text: "Conforme exigido pela Lei 25, a CENA nomeou um Responsável pela Privacidade (Responsável pela proteção dos dados pessoais).",
      officer_contact: "Contacto: info1@cena-ca.org",
      officer_role: "Papel: Supervisiona a segurança dos dados, trata pedidos de acesso e gere o \"Registo de Incidentes de Confidencialidade\".",
      security_title: "Medidas de Segurança",
      security_text: "Implementamos salvaguardas tecnológicas (encriptação e alojamento seguro) para evitar acessos não autorizados. No caso de uma violação de dados que apresente um \"risco de lesão grave\", notificaremos imediatamente a Commission d’accès à l’information du Québec (CAI) e os utilizadores afetados.",
      rights_title: "Os Seus Direitos (O \"Direito ao Esquecimento\")",
      rights_list: "Tem o direito a:",
      rights_portability: "Acesso e Portabilidade: Receber os seus dados num formato tecnológico estruturado.",
      rights_deindexing: "Desindexação: Solicitar que a CENA pare de divulgar as suas informações pessoais ou as apague inteiramente dos nossos registos digitais.",
      agree_terms: "Concordo com a Política de Privacidade e os termos de Proteção de Dados."
    },
    terms: {
      headline: "TERMOS DE USO",
      subheadline: "Governança CENA e Termos de Serviço",
      section1_title: "01. Aceitação dos Termos",
      section1_text: "Ao aceder a este website, concorda em cumprir estes Termos de Uso e todas as leis e regulamentos aplicáveis no Canadá e no Quebec.",
      section2_title: "02. Licença de Uso",
      section2_text: "É concedida permissão para descarregar temporariamente uma cópia dos materiais (informação ou software) no website da CENA apenas para visualização transitória pessoal e não comercial.",
      section3_title: "03. Governança",
      section3_text: "Qualquer reivindicação relativa ao website da CENA será regida pelas leis da Província do Quebec, sem consideração ao seu conflito de disposições legais.",
      footer_text: "Termos de Uso © CENA 2026. Entidade legal NEQ: 1181556193."
    },
    cookies: {
      title: "Gestão de Cookies",
      description: "Utilizamos cookies para melhorar a sua experiência. Em conformidade com a Lei 25, garantimos a proteção dos seus dados e o seu direito de escolha.",
      accept: "Aceitar",
      decline: "Recusar"
    },
    gallery: {
      badge: 'COMUNIDADE',
      title: 'NATAL SOLIDÁRIO',
      subtitle: '"Transformando o Natal em sorrisos e esperança."',
      explore_instruction: 'Explorar a Galeria Arquitetônica'
    },
    featured_event: {
      badge: 'Evento em Destaque',
      title: 'DIA DA CONSCIÊNCIA NEGRA',
      subtitle: 'Celebração da herança, do orgulho e da excelência negra no Canadá',
      date: '28 de fevereiro de 2026 — Longueuil',
      cta: 'Explorar a Galeria'
    },
    subject: {
      label: 'Assunto',
      placeholder: 'Selecionar um assunto',
      membership: '01 CENA ACADEMY',
      volunteer: '06 PROGRAMA DE VOLUNTARIADO',
      programs: '03 GERAÇÃO INOVAÇÃO',
      events: 'Eventos',
      partnership: 'Parceria',
      sponsorship: 'Patrocínio',
      other: 'Outro',
      elite_women: '02 ELITE FEMININA',
      mentoring_circle: '04 CÍRCULO DE MENTORIA',
      entrepreneur_hub: '05 HUB EMPREENDEDOR'
    },
    footer: {
      contact_bureau: 'Contacto do Escritório',
      follow_us: 'Siga-nos',
      get_in_touch: 'Contacto & Acesso',
      our_location: 'Sede Social',
      location_text: '3181 Montée Saint-hubert, QC, Canada',
      phone: 'Telefone Office',
      email: 'Ligação Direta',
      about_cena: 'Missão Institucional',
      about_text: 'A CENA é a organização de referência para o sucesso angolano e lusófono no Canadá.',
      send_message: 'Ligação Estratégica',
      your_name: 'Nome completo',
      your_email: 'Endereço de e-mail',
      subject: 'Assunto do pedido',
      your_message: 'Sua mensagem ou proposta',
      send_message_btn: 'Transmitir o pedido',
      quick_links: 'Links Rápidos',
      legal: 'Avisos Legais',
      privacy_policy: 'Confidencialidade de dados',
      terms_of_service: 'Termos e Condições',
      description: 'Comunidade de Educação e Networking Angolana.',
      copyright: "© 2026 CENA – Comunidade de Educação e Networking Angolana. Todos os direitos reservados.",
      built_with_love: "Powered by ProjectionAI"
    }
  }
};