import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'fr' | 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('fr');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('cena-language') as Language;
    if (savedLanguage && ['fr', 'en', 'pt'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('cena-language', language);
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// Translation data
const translations = {
  fr: {
    common: {
      donate_now: 'Faire un don',
      read_more: 'Lire plus',
      learn_more: 'En savoir plus',
      show_less: 'Voir moins',
      contact_us: 'Nous contacter',
      get_involved: 'S\'impliquer',
      view_all: 'Voir tout',
      sign_up: 'S\'inscrire',
      join_us: 'Rejoignez-nous',
      trusted_by: 'Ils nous font confiance'
    },
    navigation: {
      home: 'Accueil',
      about: 'À propos',
      mission: 'Mission',
      vision: 'Vision',
      programs: 'Programmes',
      partners: 'Partenaires',
      members: 'Membres',
      events: 'Événements',
      team: 'Équipe',
      support: 'Soutien',
      blog: 'Blog',
      contact: 'Contact'
    },
    hero: {
      title: 'Autonomiser, Connecter et Transformer',
      subtitle: 'Par l\'éducation, l\'entrepreneuriat et le réseautage',
      description: 'CENA (Comunidade de Educação e Networking Angolana) est une communauté vivante et évolutive dédiée au développement éducatif, des affaires et communautaire de la diaspora angolaise et lusophone au Canada.',
      cta_primary: 'Soutenez Notre Mission',
      cta_secondary: 'Découvrez Nos Programmes',
      members_connected: 'Membres Connectés',
      active_programs: 'Programmes Actifs',
      partners: 'Partenaires'
    },
    about: {
      badge: 'À propos de CENA',
      title: 'Une communauté en mouvement',
      description: 'CENA incarne la transformation de la diaspora angolaise et lusophone au Canada. Nous sommes dédiés à l\'excellence en éducation, entrepreneuriat et réseautage stratégique.',
      who_we_are: 'Qui nous sommes',
      who_we_are_text: 'CENA est une organisation dédiée à l\'autonomisation de la diaspora angolaise et lusophone au Canada par l\'éducation, l\'entrepreneuriat et le réseautage collaboratif. Nous créons des espaces d\'apprentissage, de croissance et de connexion.',
      our_approach: 'Notre approche',
      our_approach_text: 'Nous croyons au pouvoir de la communauté, de l\'éducation et de l\'action collaborative. Notre approche combine programmes éducatifs, développement des affaires et réseautage pour transformer des vies.',
      stats_title: 'Nos Objectifs d\'ici trois ans',
      stats: {
        members: 'Membres Actifs',
        workshops: 'Ateliers Organisés',
        partnerships: 'Partenariats',
        years: 'Années d\'Impact'
      }
    },
    mission: {
      badge: 'Notre Mission',
      title: 'Autonomiser, Connecter et Transformer',
      description: 'Notre mission est de favoriser l\'autonomisation, la connexion et la transformation des personnes à travers l\'éducation, l\'entrepreneuriat et le réseautage collaboratif.',
      pillar1_title: 'Éducation',
      pillar1_desc: 'Fournir des ressources éducatives et des opportunités d\'apprentissage pour le développement personnel et professionnel.',
      pillar2_title: 'Entrepreneuriat',
      pillar2_desc: 'Soutenir les entreprises et initiatives entrepreneuriales au sein de la communauté angolaise et lusophone.',
      pillar3_title: 'Réseautage',
      pillar3_desc: 'Créer des connexions significatives qui renforcent la communauté et ouvrent de nouvelles opportunités.'
    },
    vision: {
      badge: 'Notre Vision',
      title: 'Devenir une référence',
      description: 'Notre vision est de devenir une référence dans le développement éducatif, des affaires et communautaire pour la diaspora angolaise et lusophone au Canada.',
      goal1: 'Excellence Éducative',
      goal1_desc: 'Établir des programmes éducatifs reconnus qui soutiennent l\'apprentissage tout au long de la vie.',
      goal2: 'Croissance Économique',
      goal2_desc: 'Favoriser la croissance économique grâce à l\'entrepreneuriat et au développement des affaires.',
      goal3: 'Impact Communautaire',
      goal3_desc: 'Créer un impact durable qui profite à l\'ensemble de la communauté lusophone au Canada.'
    },
    programs: {
      badge: 'Nos Programmes',
      title: 'Programmes d\'Impact',
      description: 'Des initiatives ciblées qui soutiennent l\'éducation, l\'entrepreneuriat et le développement communautaire à travers le réseautage et la collaboration.',
      
      academy_title: 'CENA Academy',
      academy_description: 'Développement des compétences professionnelles et académiques.',
      academy_impact: 'Éducation Continue',
      academy_details: 'CENA Academy offre des cours, ateliers et certifications dans divers domaines professionnels. Notre programme éducatif structuré aide les membres à acquérir de nouvelles compétences, à avancer dans leur carrière et à s\'adapter au marché du travail canadien.',
      
      women_title: 'Femmes en Leadership',
      women_description: 'Autonomisation du leadership féminin dans la communauté.',
      women_impact: 'Leadership Féminin',
      women_details: 'Ce programme soutient les femmes dans leur parcours de leadership à travers le mentorat, les ateliers de développement des compétences et les opportunités de réseautage. Nous créons un espace pour les femmes leaders d\'inspirer, de se soutenir mutuellement et de croître ensemble.',
      
      youth_title: 'Innovation Jeunesse',
      youth_description: 'Inspirer et équiper la prochaine génération de leaders.',
      youth_impact: 'Jeunesse Innovante',
      youth_details: 'Notre programme d\'innovation jeunesse engage les jeunes membres dans des projets créatifs, le développement de compétences technologiques et les initiatives entrepreneuriales. Nous cultivons la créativité, l\'innovation et le leadership chez les jeunes de notre communauté.',
      
      mentorship_title: 'Mentorat',
      mentorship_description: 'Mentors expérimentés accompagnant membres en développement.',
      mentorship_impact: 'Mentorat Actif',
      mentorship_details: 'Notre programme de mentorat connecte des professionnels expérimentés avec des membres cherchant des conseils dans leur carrière, leurs affaires ou leur développement personnel. Des sessions structurées garantissent des relations de mentorat significatives et impactantes.',
      
      entrepreneurship_title: 'Entrepreneuriat',
      entrepreneurship_description: 'Soutien complet pour entrepreneurs et propriétaires d\'entreprises.',
      entrepreneurship_impact: 'Soutien aux Affaires',
      entrepreneurship_details: 'Notre programme d\'entrepreneuriat fournit aux propriétaires d\'entreprises les ressources, le mentorat et les connexions nécessaires pour réussir. Nous organisons des événements de pitch, facilitons l\'accès au financement et créons des opportunités de réseautage qui mènent à la croissance.',
      
      integration_title: 'Intégration Communautaire',
      integration_description: 'Soutien aux nouveaux arrivants pour s\'intégrer au Canada.',
      integration_impact: 'Nouveaux Arrivants',
      integration_details: 'Nous aidons les nouveaux arrivants à naviguer dans la vie au Canada à travers l\'orientation culturelle, les services de référence, l\'assistance linguistique et les événements de construction communautaire. Notre objectif est de faciliter une intégration réussie et un sentiment d\'appartenance.',
      
      events_title: 'Événements & Ateliers',
      events_description: 'Événements, ateliers et activités de renforcement communautaire.',
      events_impact: 'Événements Annuels',
      events_details: 'Nous organisons une variété d\'événements incluant des ateliers professionnels, des célébrations culturelles, des soirées de réseautage et des séminaires éducatifs. Ces événements créent des opportunités de connexion, d\'apprentissage et de célébration de notre culture.',
      
      volunteer_title: 'Programmes de Bénévolat',
      volunteer_description: 'Opportunités pour contribuer et faire une différence ensemble.',
      volunteer_impact: 'Bénévoles Actifs',
      volunteer_details: 'Nos programmes de bénévolat offrent des opportunités significatives de contribuer à notre communauté. Les bénévoles soutiennent nos événements, programmes et initiatives tout en développant de nouvelles compétences et en créant des connexions.',
      
      join_program_title: 'Prêt à vous joindre à nos programmes?',
      join_program_description: 'Que vous cherchiez à apprendre, à développer votre entreprise ou à vous connecter, nous avons un programme pour vous.',
      join_program_button: 'Devenir Membre'
    },
    partners: {
      badge: 'Nos Partenaires',
      title: 'Construire ensemble',
      description: 'Nous collaborons avec des organisations qui partagent notre vision de l\'autonomisation communautaire et du développement.',
      partner_type_corporate: 'Partenaires Corporatifs',
      partner_type_community: 'Organisations Communautaires',
      partner_type_educational: 'Institutions Éducatives',
      partner_type_government: 'Agences Gouvernementales',
      become_partner_title: 'Devenez Partenaire',
      become_partner_desc: 'Intéressé à collaborer avec CENA? Contactez-nous pour explorer les opportunités de partenariat.',
      become_partner_button: 'Contactez-nous'
    },
    members: {
      badge: 'Nos Membres',
      title: 'Une communauté diversifiée',
      description: 'Nos membres proviennent de divers horizons, unis par un engagement commun envers l\'éducation, l\'entrepreneuriat et le développement communautaire.',
      member_benefits: 'Avantages pour les membres',
      benefit1: 'Accès à tous les programmes et ateliers',
      benefit2: 'Opportunités de réseautage',
      benefit3: 'Mentorat et soutien',
      benefit4: 'Ressources d\'affaires',
      benefit5: 'Événements communautaires',
      benefit6: 'Newsletter et mises à jour',
      join_title: 'Rejoignez Notre Communauté',
      join_desc: 'Devenez membre de CENA et connectez-vous avec des personnes partageant les mêmes idées engagées à faire une différence.',
      join_button: 'Devenir Membre'
    },
    events: {
      badge: 'Événements',
      title: 'Événements à venir',
      description: 'Joignez-vous à nous lors de nos événements réguliers conçus pour éduquer, connecter et inspirer notre communauté.',
      upcoming: 'Prochains Événements',
      event1_title: 'Atelier Développement d\'Affaires',
      event1_location: 'Centre Communautaire de Montréal',
      coming_soon: 'À venir',
      event1_description: 'Apprenez les stratégies essentielles pour développer votre entreprise au Canada.',
      event1_attendees: '40 Places',
      event2_title: 'Soirée de Réseautage',
      event2_location: 'Espace CENA',
      event2_description: 'Connectez-vous avec des professionnels et des entrepreneurs de notre communauté.',
      event2_attendees: '60 Participants',
      event3_title: 'Célébration Culturelle',
      event3_location: 'Centre Communautaire',
      event3_description: 'Célébrez la culture angolaise et lusophone avec musique, nourriture et danse.',
      event3_attendees: '150 Invités',
      type_workshop: 'Atelier',
      type_networking: 'Réseautage',
      type_cultural: 'Culturel',
      register_now: 'S\'inscrire',
      past_events: 'Événements Passés',
      past_event_success: 'Plus de 500 participants à nos événements cette année'
    },
    team: {
      badge: 'Notre Équipe',
      title: 'Rencontrez Notre Leadership',
      description: 'Notre Conseil d\'Administration dévoué guide CENA dans sa mission d\'autonomiser la diaspora angolaise et lusophone au Canada.',
      role_president: 'Présidente / PDG',
      role_vp_operations: 'Vice-Présidente des Opérations',
      role_finance: 'Directeur des Finances',
      role_communication: 'Directrice de Communication & Médias',
      role_business: 'Directeur du Développement des Affaires',
      role_training: 'Directrice de Formation & Mentorat',
      role_hr: 'Directrice des Ressources Humaines',
      role_international: 'Directrice des Relations Internationales',
      role_events: 'Directrice des Événements & Engagement',
      role_youth: 'Directeur de la Jeunesse & Innovation',
      leadership_title: 'Message de Leadership',
      leadership_message: 'Ensemble, nous construisons une communauté forte, unie par l\'éducation, l\'entrepreneuriat et le réseautage. Notre engagement est de créer des opportunités qui transforment des vies et renforcent les liens communautaires à travers le Canada et au-delà.'
    },
    support: {
      badge: 'Soutenez-nous',
      title: 'Aidez-nous à avoir un impact',
      description: 'Votre soutien nous aide à élargir nos programmes et à atteindre plus de membres de la communauté. Il existe de nombreuses façons de contribuer.',
      donate_title: 'Faire un Don',
      donate_description: 'Votre soutien financier alimente nos programmes et initiatives.',
      choose_amount: 'Choisir un montant ($)',
      custom_amount: 'Montant personnalisé',
      donation_message: 'Message de don (Optionnel)',
      donation_message_placeholder: 'Laissez un message de soutien...',
      tax_notice: 'Les reçus fiscaux sont disponibles pour les dons admissibles.',
      secure_payment: 'Paiement sécurisé via PayPal • Redirige vers PayPal.com',
      other_ways: 'Autres façons d\'aider',
      volunteer_title: 'Bénévolat',
      volunteer_description: 'Rejoignez notre équipe de bénévoles et contribuez directement à nos programmes.',
      sponsor_title: 'Parrainage',
      sponsor_description: 'Parrainez un événement ou un programme et obtenez de la visibilité pour votre marque.',
      impact_title: 'Votre Impact',
      impact_50: 'Soutient un participant d\'atelier',
      impact_100: 'Finance un événement de réseautage',
      impact_250: 'Parraine une session de mentorat',
      impact_500: 'Soutient un programme complet'
    },
    blog: {
      badge: 'Blog & Actualités',
      title: 'Dernières nouvelles',
      description: 'Restez informé de nos derniers programmes, événements et histoires de réussite communautaire.',
      read_full: 'Lire l\'article complet',
      view_all_posts: 'Voir tous les articles',
      article1_title: 'Programme d\'entrepreneuriat',
      article1_excerpt: 'CENA lance un programme d\'entrepreneuriat pour soutenir les entreprises angolaises et lusophones au Canada.',
      article1_full: 'Notre nouveau programme d\'entrepreneuriat offre aux propriétaires d\'entreprises aspirants et établis les ressources, le mentorat et les connexions dont ils ont besoin pour réussir dans le paysage commercial canadien. Le programme comprend des ateliers mensuels, des opportunités de mentorat individuel, un accès à des experts de l\'industrie et des événements de réseautage qui connectent les entrepreneurs avec des clients et partenaires potentiels. Nous sommes ravis de soutenir la croissance des entreprises communautaires et de contribuer au succès économique de notre diaspora.',
      article1_author: 'Équipe CENA',
      article1_read_time: '4 min de lecture',
      article1_category: 'Programmes',
      posted: 'Publié',
      article2_title: 'Soirée de réseautage record',
      article2_excerpt: 'Plus de 80 professionnels se sont réunis lors de notre plus grand événement de réseautage, créant des connexions significatives.',
      article2_full: 'Notre récente soirée de réseautage a été un succès retentissant, avec plus de 80 professionnels de divers secteurs se réunissant pour se connecter, partager des idées et explorer des opportunités de collaboration. L\'événement a présenté des séances de réseautage structurées, des discussions de groupe et des présentations d\'entreprises locales. Les participants ont exprimé leur appréciation pour la qualité des connexions établies et l\'énergie positive de la soirée. Nous sommes impatients d\'organiser d\'autres événements de cette envergure.',
      article2_author: 'Équipe CENA',
      article2_read_time: '3 min de lecture',
      article2_category: 'Événements',
      article3_title: 'Nouveaux partenariats éducatifs',
      article3_excerpt: 'CENA s\'associe à trois institutions éducatives pour étendre l\'accès aux programmes de formation.',
      article3_full: 'Nous sommes ravis d\'annoncer de nouveaux partenariats avec trois institutions éducatives de premier plan qui permettront aux membres de CENA d\'accéder à des programmes de formation spécialisés, des ateliers de développement professionnel et des ressources d\'apprentissage en ligne. Ces partenariats reflètent notre engagement à fournir des opportunités éducatives de haute qualité à notre communauté et à soutenir l\'apprentissage tout au long de la vie. Des détails supplémentaires sur les programmes spécifiques seront annoncés prochainement.',
      article3_author: 'Équipe CENA',
      article3_read_time: '3 min de lecture',
      article3_category: 'Partenariats',
      testimonial1_name: 'Ana Ferreira',
      testimonial1_role: 'Entrepreneure',
      testimonial1_quote: 'CENA m\'a fourni le mentorat et les connexions dont j\'avais besoin pour lancer mon entreprise avec succès au Canada.',
      testimonial2_name: 'Carlos Mendes',
      testimonial2_role: 'Membre',
      testimonial2_quote: 'La communauté et les opportunités de réseautage chez CENA ont été inestimables pour ma croissance professionnelle.',
      testimonial3_name: 'Miguel Santos',
      testimonial3_role: 'Développeur',
      testimonial3_quote: 'Les ateliers techniques et les événements de réseautage m\'ont aidé à accélérer ma carrière dans le secteur technologique canadien.',
      testimonial4_name: 'Beatriz Lima',
      testimonial4_role: 'Consultante',
      testimonial4_quote: 'L\'intégration au Canada était difficile, mais CENA m\'a fourni les outils et le soutien pour m\'épanouir professionnellement.',
      success_stories: 'Histoires de réussite',
      newsletter_title: 'Restez Connecté',
      newsletter_description: 'Abonnez-vous à notre newsletter pour recevoir des mises à jour sur nos programmes et événements.',
      email_placeholder: 'Entrez votre courriel',
      subscribe_button: 'S\'abonner'
    },
    success: {
      badge: 'Témoignages',
      title: 'Histoires de réussite',
      description: 'Découvrez comment CENA transforme des vies à travers l\'éducation, l\'entrepreneuriat et le réseautage.',
      
      antonio_role: 'Chef',
      antonio_story: 'Grâce à CENA, j\'ai perfectionné mes compétences et ouvert mon restaurant.',
      fernando_role: 'Pizzaiolo',
      fernando_story: 'Le réseau CENA m\'a permis de lancer ma pizzeria artisanale.',
      miguel_role: 'Pâtissier',
      miguel_story: 'CENA a transformé ma passion en entreprise florissante.',
      beatriz_role: 'Infirmière',
      beatriz_story: 'CENA m\'a guidée pour faire reconnaître mes qualifications.',
      carla_role: 'Médecin',
      carla_story: 'Le mentorat a été crucial pour établir ma pratique médicale.',
      joaquina_role: 'Restauratrice',
      joaquina_story: 'CENA m\'a connectée avec des partenaires pour réaliser mon rêve.',
      torres_role: 'Boulanger',
      torres_story: 'La formation m\'a permis de créer une boulangerie prospère.',
      manuel_role: 'Épicier',
      manuel_story: 'CENA m\'a aidé à comprendre le marché et ouvrir mon épicerie.',
      domingos_role: 'Barbier',
      domingos_story: 'Grâce à CENA, j\'ai lancé mon salon et formé des jeunes.',
      isabel_role: 'Designer',
      isabel_story: 'CENA m\'a connectée avec des clients pour mon agence.',
      alberto_role: 'Ébéniste',
      alberto_story: 'Le programme m\'a permis de transformer mon savoir-faire.',
      rui_role: 'Gestionnaire',
      rui_story: 'CENA m\'a formé aux standards et je dirige une équipe.',
      jose_role: 'Consultant',
      jose_story: 'Le mentorat a accéléré ma transition vers le conseil.',
      madalena_role: 'Directrice Ventes',
      madalena_story: 'CENA m\'a donné les outils pour diriger une équipe performante.',
      francisca_role: 'Artisane',
      francisca_story: 'CENA m\'a aidée à commercialiser mes créations artisanales.',
      catarino_role: 'Styliste',
      catarino_story: 'Le réseau m\'a connecté avec des clients pour ma ligne.',
      agostinho_role: 'Conseiller Assurance',
      agostinho_story: 'CENA m\'a aidé à obtenir mes certifications et bâtir ma clientèle.',
      henriques_role: 'Analyste Financier',
      henriques_story: 'Le programme m\'a préparé pour le secteur financier.',
      bernardo_role: 'Comptable',
      bernardo_story: 'CENA m\'a soutenu dans mon parcours CPA avec succès.',
      vitoria_role: 'Agent Immobilier',
      vitoria_story: 'CENA m\'a aidée à développer mon expertise en immobilier.',
      selma_role: 'Spécialiste Marketing',
      selma_story: 'CENA m\'a ouvert des portes et je dirige des campagnes.',
      felicidade_role: 'Entrepreneure Tech',
      felicidade_story: 'Le programme d\'incubation m\'a permis de lancer ma startup.',
      mario_role: 'Développeur',
      mario_story: 'CENA m\'a connecté avec des opportunités dans la tech.',
      xavier_role: 'Avocat',
      xavier_story: 'CENA m\'a aidé à construire ma pratique juridique et mon réseau.',
      paulo_role: 'Avocat',
      paulo_story: 'Le réseau CENA m\'a aidé à établir mon cabinet et servir la communauté.'
    },
    gallery: {
      badge: 'Galerie',
      title: 'Événement de Noël',
      subtitle: 'Moments forts de notre dernière célébration',
      view_all: 'Voir toutes les photos'
    },
    footer: {
      get_in_touch: 'Contactez-nous',
      our_location: 'Notre Emplacement',
      location_text: '3181 Montée Saint-hubert, QC, Canada\\nCENA - Comunidade de Educação e Networking Angolana\\nOrganisme Communautaire',
      phone: 'Téléphone',
      email: 'Courriel',
      about_cena: 'À propos de CENA',
      about_text: 'Le CENA est reconnu comme un organisme à but non lucratif (OBNL) par les autorités fiscales du Canada et du Québec. Numéro d\'enregistrement : 1745968-8. Les dons sont déductibles d\'impôt au Canada et au Québec.',
      send_message: 'Envoyez-nous un message',
      your_name: 'Votre nom',
      your_email: 'Votre courriel',
      subject: 'Sujet',
      subject_placeholder: 'Choisir un sujet',
      subject_membership: 'Adhésion',
      subject_volunteer: 'Bénévolat',
      subject_partnership: 'Partenariat',
      subject_sponsorship: 'Parrainage',
      subject_workshop: 'Atelier',
      subject_networking: 'Événement de réseautage',
      subject_entrepreneurship: 'Programme d\'entrepreneuriat',
      subject_education: 'Programme éducatif',
      subject_other: 'Autre',
      your_message: 'Votre message',
      send_message_btn: 'Envoyer le message',
      sending: 'Envoi...',
      sent: 'Envoyé !',
      form_success: 'Message envoyé avec succès! Nous vous répondrons bientôt.',
      form_error: 'Veuillez remplir tous les champs',
      email_error: 'Veuillez entrer une adresse courriel valide',
      form_error_generic: 'Échec de l\'envoi du message. Veuillez réessayer ou nous envoyer un courriel directement.',
      quick_links: 'Liens Rapides',
      legal: 'Légal',
      privacy_policy: 'Politique de confidentialité',
      terms_of_service: 'Conditions d\'utilisation',
      description: 'Autonomiser, connecter et transformer par l\'éducation, l\'entrepreneuriat et le réseautage collaboratif.',
      copyright: '© 2025 CENA - Comunidade de Educação e Networking Angolana (Canada). Tous droits réservés.',
      built_with_love: 'Conçu avec ❤️ pour notre communauté'
    }
  },
  en: {
    common: {
      donate_now: 'Donate Now',
      read_more: 'Read More',
      learn_more: 'Learn More',
      show_less: 'Show Less',
      contact_us: 'Contact Us',
      get_involved: 'Get Involved',
      view_all: 'View All',
      sign_up: 'Sign Up',
      join_us: 'Join Us',
      trusted_by: 'Trusted By'
    },
    navigation: {
      home: 'Home',
      about: 'About',
      mission: 'Mission',
      vision: 'Vision',
      programs: 'Programs',
      partners: 'Partners',
      members: 'Members',
      events: 'Events',
      team: 'Team',
      support: 'Support',
      blog: 'Blog',
      contact: 'Contact'
    },
    hero: {
      title: 'Empower, Connect, and Transform',
      subtitle: 'Through Education, Entrepreneurship, and Networking',
      description: 'CENA (Comunidade de Educação e Networking Angolana) is a living, evolving community dedicated to educational, business, and community development for the Angolan and Lusophone diaspora in Canada.',
      cta_primary: 'Support Our Mission',
      cta_secondary: 'Explore Our Programs',
      members_connected: 'Members Connected',
      active_programs: 'Active Programs',
      partners: 'Partners'
    },
    about: {
      badge: 'About CENA',
      title: 'A community in movement',
      description: 'CENA embodies the transformation of the Angolan and Lusophone diaspora in Canada. We are dedicated to excellence in education, entrepreneurship, and strategic networking.',
      who_we_are: 'Who We Are',
      who_we_are_text: 'CENA is an organization dedicated to empowering the Angolan and Lusophone diaspora in Canada through education, entrepreneurship, and collaborative networking. We create spaces for learning, growth, and connection.',
      our_approach: 'Our Approach',
      our_approach_text: 'We believe in the power of community, education, and collaborative action. Our approach combines educational programs, business development, and networking to transform lives.',
      stats_title: 'Our Goals for the Next Three Years',
      stats: {
        members: 'Active Members',
        workshops: 'Workshops Held',
        partnerships: 'Partnerships',
        years: 'Years of Impact'
      }
    },
    mission: {
      badge: 'Our Mission',
      title: 'Empower, Connect, and Transform',
      description: 'Our mission is to foster empowerment, connection, and transformation of people through education, entrepreneurship, and collaborative networking.',
      pillar1_title: 'Education',
      pillar1_desc: 'Provide educational resources and learning opportunities for personal and professional development.',
      pillar2_title: 'Entrepreneurship',
      pillar2_desc: 'Support businesses and entrepreneurial initiatives within the Angolan and Lusophone community.',
      pillar3_title: 'Networking',
      pillar3_desc: 'Create meaningful connections that strengthen the community and open new opportunities.'
    },
    vision: {
      badge: 'Our Vision',
      title: 'Becoming a Reference',
      description: 'Our vision is to become a reference in educational, business, and community development for the Angolan and Lusophone diaspora in Canada.',
      goal1: 'Educational Excellence',
      goal1_desc: 'Establish recognized educational programs that support lifelong learning.',
      goal2: 'Economic Growth',
      goal2_desc: 'Foster economic growth through entrepreneurship and business development.',
      goal3: 'Community Impact',
      goal3_desc: 'Create lasting impact that benefits the entire Lusophone community in Canada.'
    },
    programs: {
      badge: 'Our Programs',
      title: 'Impact Programs',
      description: 'Focused initiatives that support education, entrepreneurship, and community development through networking and collaboration.',
      
      academy_title: 'CENA Academy',
      academy_description: 'Professional and academic skill development programs.',
      academy_impact: 'Education Program',
      academy_details: 'CENA Academy offers courses, workshops, and certifications in various professional fields. Our structured educational program helps members acquire new skills, advance in their careers, and adapt to the Canadian job market.',
      
      women_title: 'Women in Leadership',
      women_description: 'Empowering female leadership within the community.',
      women_impact: 'Women Leadership',
      women_details: 'This program supports women in their leadership journey through mentorship, skill development workshops, and networking opportunities. We create a space for female leaders to inspire, support each other, and grow together.',
      
      youth_title: 'Youth Innovation',
      youth_description: 'Inspiring and equipping the next generation of leaders.',
      youth_impact: 'Youth Innovation',
      youth_details: 'Our youth innovation program engages young members in creative projects, technological skill development, and entrepreneurial initiatives. We cultivate creativity, innovation, and leadership among the youth in our community.',
      
      mentorship_title: 'Mentorship',
      mentorship_description: 'Experienced mentors supporting members in development.',
      mentorship_impact: 'Active Mentorship',
      mentorship_details: 'Our mentorship program connects experienced professionals with members seeking advice in their careers, businesses, or personal development. Structured sessions ensure meaningful and impactful mentorship relationships.',
      
      entrepreneurship_title: 'Entrepreneurship',
      entrepreneurship_description: 'Comprehensive support for entrepreneurs and businesses.',
      entrepreneurship_impact: 'Business Support',
      entrepreneurship_details: 'Our entrepreneurship program provides business owners with the resources, mentorship, and connections needed to succeed. We organize pitch events, facilitate access to funding, and create networking opportunities that lead to growth.',
      
      integration_title: 'Community Integration',
      integration_description: 'Supporting newcomers to integrate and thrive in Canada.',
      integration_impact: 'New Arrivals',
      integration_details: 'We help newcomers navigate life in Canada through cultural orientation, reference services, language assistance, and community-building events. Our goal is to facilitate successful integration and a sense of belonging.',
      
      events_title: 'Events & Workshops',
      events_description: 'Events, workshops, and community-building activities.',
      events_impact: 'Annual Events',
      events_details: 'We organize a variety of events including professional workshops, cultural celebrations, networking evenings, and educational seminars. These events create opportunities for connection, learning, and celebration of our culture.',
      
      volunteer_title: 'Volunteer Programs',
      volunteer_description: 'Opportunities to contribute and make a difference together.',
      volunteer_impact: 'Active Volunteers',
      volunteer_details: 'Our volunteer programs offer significant opportunities to contribute to our community. Volunteers support our events, programs, and initiatives while developing new skills and creating connections.',
      
      join_program_title: 'Ready to join our programs?',
      join_program_description: 'Whether you\'re looking to learn, grow your business, or connect, we have a program for you.',
      join_program_button: 'Become a Member'
    },
    partners: {
      badge: 'Our Partners',
      title: 'Building Together',
      description: 'We collaborate with organizations that share our vision of community empowerment and development.',
      partner_type_corporate: 'Corporate Partners',
      partner_type_community: 'Community Organizations',
      partner_type_educational: 'Educational Institutions',
      partner_type_government: 'Government Agencies',
      become_partner_title: 'Become a Partner',
      become_partner_desc: 'Interested in collaborating with CENA? Contact us to explore partnership opportunities.',
      become_partner_button: 'Contact Us'
    },
    members: {
      badge: 'Our Members',
      title: 'A diverse community',
      description: 'Our members come from diverse backgrounds, united by a shared commitment to education, entrepreneurship, and community development.',
      member_benefits: 'Member Benefits',
      benefit1: 'Access to all programs and workshops',
      benefit2: 'Networking opportunities',
      benefit3: 'Mentorship and support',
      benefit4: 'Business resources',
      benefit5: 'Community events',
      benefit6: 'Newsletter and updates',
      join_title: 'Join Our Community',
      join_desc: 'Become a CENA member and connect with like-minded individuals committed to making a difference.',
      join_button: 'Become a Member'
    },
    events: {
      badge: 'Events',
      title: 'Upcoming Events',
      description: 'Join us at our regular events designed to educate, connect, and inspire our community.',
      upcoming: 'Upcoming Events',
      event1_title: 'Business Development Workshop',
      event1_location: 'Montreal Community Center',
      coming_soon: 'Coming Soon',
      event1_description: 'Learn essential strategies for growing your business in Canada.',
      event1_attendees: '40 Spots',
      event2_title: 'Networking Evening',
      event2_location: 'CENA Space',
      event2_description: 'Connect with professionals and entrepreneurs from our community.',
      event2_attendees: '60 Participants',
      event3_title: 'Cultural Celebration',
      event3_location: 'Community Center',
      event3_description: 'Celebrate Angolan and Lusophone culture with music, food, and dance.',
      event3_attendees: '150 Guests',
      type_workshop: 'Workshop',
      type_networking: 'Networking',
      type_cultural: 'Cultural',
      register_now: 'Register',
      past_events: 'Past Events',
      past_event_success: 'Over 500 attendees at our events this year'
    },
    team: {
      badge: 'Our Team',
      title: 'Meet Our Leadership',
      description: 'Our dedicated leadership team guides CENA in its mission to empower the Angolan and Lusophone diaspora in Canada.',
      role_president: 'President / CEO',
      role_vp_operations: 'Vice President of Operations',
      role_finance: 'Director of Finance',
      role_communication: 'Director of Communication & Media',
      role_business: 'Director of Business Development',
      role_training: 'Director of Training & Mentoring',
      role_hr: 'Director of Human Resources',
      role_international: 'Director of International Relations',
      role_events: 'Director of Events & Engagement',
      role_youth: 'Director of Youth & Innovation',
      leadership_title: 'Leadership Message',
      leadership_message: 'Together, we build a strong community united by education, entrepreneurship, and networking. Our commitment is to create opportunities that transform lives and strengthen community ties across Canada and beyond.'
    },
    support: {
      badge: 'Support Us',
      title: 'Help Us Make an Impact',
      description: 'Your support helps us expand our programs and reach more community members. There are many ways to contribute.',
      donate_title: 'Make a Donation',
      donate_description: 'Your financial support fuels our programs and initiatives.',
      choose_amount: 'Choose Amount ($)',
      custom_amount: 'Custom amount',
      donation_message: 'Donation Message (Optional)',
      donation_message_placeholder: 'Leave a message of support...',
      tax_notice: 'Tax receipts are available for eligible donations.',
      secure_payment: 'Secure payment via PayPal • Redirects to PayPal.com',
      other_ways: 'Other Ways to Help',
      volunteer_title: 'Volunteer',
      volunteer_description: 'Join our volunteer team and contribute directly to our programs.',
      sponsor_title: 'Sponsorship',
      sponsor_description: 'Sponsor an event or program and gain visibility for your brand.',
      impact_title: 'Your Impact',
      impact_50: 'Supports one workshop participant',
      impact_100: 'Funds a networking event',
      impact_250: 'Sponsors a mentorship session',
      impact_500: 'Supports a complete program'
    },
    blog: {
      badge: 'Blog & News',
      title: 'Latest News',
      description: 'Stay informed about our latest programs, events, and community success stories.',
      read_full: 'Read Full Article',
      view_all_posts: 'View All Posts',
      article1_title: 'New Entrepreneurship Program',
      article1_excerpt: 'CENA launches an entrepreneurship program to support Angolan and Lusophone businesses in Canada.',
      article1_full: 'Our new entrepreneurship program provides aspiring and established business owners with the resources, mentorship, and connections they need to succeed in the Canadian business landscape. The program includes monthly workshops, one-on-one mentorship opportunities, access to industry experts, and networking events that connect entrepreneurs with potential clients and partners. We\'re excited to support the growth of community businesses and contribute to the economic success of our diaspora.',
      article1_author: 'CENA Team',
      article1_read_time: '4 min read',
      article1_category: 'Programs',
      posted: 'Posted',
      article2_title: 'Record Networking Evening',
      article2_excerpt: 'Over 80 professionals gathered at our largest networking event, creating meaningful connections.',
      article2_full: 'Our recent networking evening was a resounding success, with over 80 professionals from various industries coming together to connect, share ideas, and explore collaboration opportunities. The event featured structured networking sessions, panel discussions, and presentations from local businesses. Attendees expressed appreciation for the quality of connections made and the positive energy of the evening. We look forward to hosting more events of this scale.',
      article2_author: 'CENA Team',
      article2_read_time: '3 min read',
      article2_category: 'Events',
      article3_title: 'New Educational Partnerships',
      article3_excerpt: 'CENA partners with three educational institutions to expand access to training programs.',
      article3_full: 'We\'re thrilled to announce new partnerships with three leading educational institutions that will enable CENA members to access specialized training programs, professional development workshops, and online learning resources. These partnerships reflect our commitment to providing high-quality educational opportunities to our community and supporting lifelong learning. Additional details about specific programs will be announced soon.',
      article3_author: 'CENA Team',
      article3_read_time: '3 min read',
      article3_category: 'Partnerships',
      testimonial1_name: 'Ana Ferreira',
      testimonial1_role: 'Entrepreneur',
      testimonial1_quote: 'CENA provided me with the mentorship and connections I needed to successfully launch my business in Canada.',
      testimonial2_name: 'Carlos Mendes',
      testimonial2_role: 'Member',
      testimonial2_quote: 'The community and networking opportunities at CENA have been invaluable for my professional growth.',
      testimonial3_name: 'Miguel Santos',
      testimonial3_role: 'Developer',
      testimonial3_quote: 'The technical workshops and networking events helped me accelerate my career in the Canadian tech sector.',
      testimonial4_name: 'Beatriz Lima',
      testimonial4_role: 'Consultant',
      testimonial4_quote: 'Integrating into Canada was challenging, but CENA provided me with the tools and support to thrive professionally.',
      success_stories: 'Success Stories',
      newsletter_title: 'Stay Connected',
      newsletter_description: 'Subscribe to our newsletter to receive updates about our programs and events.',
      email_placeholder: 'Enter your email',
      subscribe_button: 'Subscribe'
    },
    success: {
      badge: 'Testimonials',
      title: 'Success Stories',
      description: 'Discover how CENA transforms lives through education, entrepreneurship, and networking.',
      
      antonio_role: 'Chef',
      antonio_story: 'Thanks to CENA, I perfected my skills and opened my restaurant.',
      fernando_role: 'Pizzaiolo',
      fernando_story: 'The CENA network helped me launch my artisanal pizzeria.',
      miguel_role: 'Pastry Chef',
      miguel_story: 'CENA transformed my passion into a thriving business.',
      beatriz_role: 'Nurse',
      beatriz_story: 'CENA guided me in getting my qualifications recognized.',
      carla_role: 'Physician',
      carla_story: 'The mentorship was crucial to establish my medical practice.',
      joaquina_role: 'Restaurant Owner',
      joaquina_story: 'CENA connected me with partners to realize my dream.',
      torres_role: 'Baker',
      torres_story: 'The training allowed me to create a thriving bakery.',
      manuel_role: 'Grocer',
      manuel_story: 'CENA helped me understand the market and open my store.',
      domingos_role: 'Barber',
      domingos_story: 'Thanks to CENA, I launched my shop and trained youth.',
      isabel_role: 'Designer',
      isabel_story: 'CENA connected me with clients for my design agency.',
      alberto_role: 'Cabinetmaker',
      alberto_story: 'The program helped me transform my craftsmanship.',
      rui_role: 'Manager',
      rui_story: 'CENA trained me to standards and I now manage a team.',
      jose_role: 'Consultant',
      jose_story: 'The mentorship accelerated my transition to consulting.',
      madalena_role: 'Sales Director',
      madalena_story: 'CENA gave me the tools to lead a high-performing team.',
      francisca_role: 'Artisan',
      francisca_story: 'CENA helped me commercialize my artisanal creations.',
      catarino_role: 'Fashion Designer',
      catarino_story: 'The network connected me with clients for my line.',
      agostinho_role: 'Insurance Advisor',
      agostinho_story: 'CENA helped me obtain certifications and build my clientele.',
      henriques_role: 'Financial Analyst',
      henriques_story: 'The program prepared me for the financial sector.',
      bernardo_role: 'Accountant',
      bernardo_story: 'CENA supported my CPA journey successfully.',
      vitoria_role: 'Real Estate Agent',
      vitoria_story: 'CENA helped me develop my expertise in real estate.',
      selma_role: 'Marketing Specialist',
      selma_story: 'CENA opened doors and I now lead campaigns.',
      felicidade_role: 'Tech Entrepreneur',
      felicidade_story: 'The incubation program allowed me to launch my startup.',
      mario_role: 'Developer',
      mario_story: 'CENA connected me with tech opportunities.',
      xavier_role: 'Lawyer',
      xavier_story: 'CENA helped me build my legal practice and network.',
      paulo_role: 'Lawyer',
      paulo_story: 'The CENA network helped me establish my practice and serve the community.'
    },
    gallery: {
      badge: 'Gallery',
      title: 'Christmas Event',
      subtitle: 'Highlights from our latest celebration',
      view_all: 'View all photos'
    },
    footer: {
      get_in_touch: 'Get in Touch',
      our_location: 'Our Location',
      location_text: '3181 Montée Saint-hubert, QC, Canada\\nCENA - Comunidade de Educação e Networking Angolana\\nCommunity Organization',
      phone: 'Phone',
      email: 'Email',
      about_cena: 'About CENA',
      about_text: 'CENA is recognized as a Non-Profit Organization (OBNL) by the Canadian and Quebec Tax Authorities. Registration number: 1745968-8. Donations are tax-deductible in Canada and Quebec.',
      send_message: 'Send us a Message',
      your_name: 'Your Name',
      your_email: 'Your Email',
      subject: 'Subject',
      subject_placeholder: 'Select a subject',
      subject_membership: 'Membership',
      subject_volunteer: 'Volunteer',
      subject_partnership: 'Partnership',
      subject_sponsorship: 'Sponsorship',
      subject_workshop: 'Workshop',
      subject_networking: 'Networking Event',
      subject_entrepreneurship: 'Entrepreneurship Program',
      subject_education: 'Education Program',
      subject_other: 'Other',
      your_message: 'Your Message',
      send_message_btn: 'Send Message',
      sending: 'Sending...',
      sent: 'Sent!',
      form_success: 'Message sent successfully! We\'ll get back to you soon.',
      form_error: 'Please fill in all fields',
      email_error: 'Please enter a valid email address',
      form_error_generic: 'Failed to send message. Please try again or email us directly.',
      quick_links: 'Quick Links',
      legal: 'Legal',
      privacy_policy: 'Privacy Policy',
      terms_of_service: 'Terms of Service',
      description: 'Empower, connect, and transform through education, entrepreneurship, and collaborative networking.',
      copyright: '© 2025 CENA - Comunidade de Educação e Networking Angolana (Canadá). All rights reserved.',
      built_with_love: 'Built with ❤️ for our community'
    }
  },
  pt: {
    common: {
      donate_now: 'Doar Agora',
      read_more: 'Ler Mais',
      learn_more: 'Saber Mais',
      show_less: 'Mostrar Menos',
      contact_us: 'Contacte-nos',
      get_involved: 'Participar',
      view_all: 'Ver Todos',
      sign_up: 'Inscrever-se',
      join_us: 'Junte-se a Nós',
      trusted_by: 'Eles confiam em nós'
    },
    navigation: {
      home: 'Início',
      about: 'Sobre',
      mission: 'Missão',
      vision: 'Visão',
      programs: 'Programas',
      partners: 'Parceiros',
      members: 'Membros',
      events: 'Eventos',
      team: 'Equipe',
      support: 'Apoio',
      blog: 'Blog',
      contact: 'Contato'
    },
    hero: {
      title: 'Capacitar, Conectar e Transformar',
      subtitle: 'Através da Educação, Empreendedorismo e Networking',
      description: 'CENA (Comunidade de Educação e Networking Angolana) é uma comunidade viva e em evolução dedicada ao desenvolvimento educacional, empresarial e comunitário da diáspora angolana e lusófona no Canadá.',
      cta_primary: 'Apoie Nossa Missão',
      cta_secondary: 'Explore Nossos Programas',
      members_connected: 'Membros Conectados',
      active_programs: 'Programas Ativos',
      partners: 'Parceiros'
    },
    about: {
      badge: 'Sobre CENA',
      title: 'Uma comunidade em movimento',
      description: 'CENA personifica a transformação da diáspora angolana e lusófona no Canadá. Somos dedicados à excelência em educação, empreendedorismo e networking estratégico.',
      who_we_are: 'Quem Somos',
      who_we_are_text: 'CENA é uma organização dedicada a capacitar a diáspora angolana e lusófona no Canadá através da educação, empreendedorismo e networking colaborativo. Criamos espaços para aprendizagem, crescimento e conexão.',
      our_approach: 'Nossa Abordagem',
      our_approach_text: 'Acreditamos no poder da comunidade, educação e ação colaborativa. Nossa abordagem combina programas educacionais, desenvolvimento empresarial e networking para transformar vidas.',
      stats_title: 'Nossos Objetivos para os Próximos Três Anos',
      stats: {
        members: 'Membros Ativos',
        workshops: 'Workshops Realizados',
        partnerships: 'Parcerias',
        years: 'Anos de Impacto'
      }
    },
    mission: {
      badge: 'Nossa Missão',
      title: 'Capacitar, Conectar e Transformar',
      description: 'Nossa missão é promover a capacitação, conexão e transformação de pessoas através da educação, empreendedorismo e networking colaborativo.',
      pillar1_title: 'Educação',
      pillar1_desc: 'Fornecer recursos educacionais e oportunidades de aprendizagem para desenvolvimento pessoal e profissional.',
      pillar2_title: 'Empreendedorismo',
      pillar2_desc: 'Apoiar negócios e iniciativas empreendedoras dentro da comunidade angolana e lusófona.',
      pillar3_title: 'Networking',
      pillar3_desc: 'Criar conexões significativas que fortalecem a comunidade e abrem novas oportunidades.'
    },
    vision: {
      badge: 'Nossa Visão',
      title: 'Tornar-se uma Referência',
      description: 'Nossa visão é tornar-se uma referência no desenvolvimento educacional, empresarial e comunitário para a diáspora angolana e lusófona no Canadá.',
      goal1: 'Excelência Educacional',
      goal1_desc: 'Estabelecer programas educacionais reconhecidos que apoiam a aprendizagem ao longo da vida.',
      goal2: 'Crescimento Económico',
      goal2_desc: 'Promover o crescimento económico através do empreendedorismo e desenvolvimento empresarial.',
      goal3: 'Impacto Comunitário',
      goal3_desc: 'Criar impacto duradouro que beneficia toda a comunidade lusófona no Canadá.'
    },
    programs: {
      badge: 'Nossos Programas',
      title: 'Programas de Impacto',
      description: 'Iniciativas focadas que apoiam educação, empreendedorismo e desenvolvimento comunitário através de networking e colaboração.',
      
      academy_title: 'CENA Academy',
      academy_description: 'Desenvolvimento de competências profissionais e académicas.',
      academy_impact: 'Educação Contínua',
      academy_details: 'CENA Academy oferece cursos, workshops e certificações em diversos domínios profissionais. Nosso programa educacional estruturado ajuda os membros a adquirir novas competências, avançar em suas carreiras e se adaptar ao mercado de trabalho canadense.',
      
      women_title: 'Mulheres em Liderança',
      women_description: 'Autonomização da liderança feminina na comunidade.',
      women_impact: 'Liderança Feminina',
      women_details: 'Este programa apoia as mulheres em seu percurso de liderança através de mentorias, workshops de desenvolvimento de competências e oportunidades de networking. Criamos um espaço para líderes femininas inspirarem, se apoiarem mutuamente e crescerem juntas.',
      
      youth_title: 'Inovação Juvenil',
      youth_description: 'Inspirar e equipar a próxima geração de líderes.',
      youth_impact: 'Juventude Inovadora',
      youth_details: 'Nosso programa de inovação juvenil envolve membros jovens em projetos criativos, desenvolvimento de competências tecnológicas e iniciativas empresariais. Cultivamos criatividade, inovação e liderança entre os jovens de nossa comunidade.',
      
      mentorship_title: 'Mentoria',
      mentorship_description: 'Mentores experientes apoiando membros em desenvolvimento.',
      mentorship_impact: 'Mentoria Ativa',
      mentorship_details: 'Nosso programa de mentoria conecta profissionais experientes com membros que buscam conselhos em suas carreiras, negócios ou desenvolvimento pessoal. Sessões estruturadas garantem relações de mentoria significativas e impactantes.',
      
      entrepreneurship_title: 'Empreendedorismo',
      entrepreneurship_description: 'Apoio completo para empreendedores e empresários.',
      entrepreneurship_impact: 'Apoio Business',
      entrepreneurship_details: 'Nosso programa de empreendedorismo fornece aos proprietários de negócios os recursos, mentoria e conexões necessárias para ter sucesso. Organizamos eventos de pitch, facilitamos o acesso a financiamento e criamos oportunidades de networking que levam ao crescimento.',
      
      integration_title: 'Integração Comunitária',
      integration_description: 'Apoio aos novos chegados para se integrarem no Canadá.',
      integration_impact: 'Novos Membros',
      integration_details: 'Ajudamos os novos chegados a navegar na vida no Canadá através de orientação cultural, serviços de referência, assistência linguística e eventos de construção comunitária. Nosso objetivo é facilitar uma integração bem-sucedida e um sentimento de pertencimento.',
      
      events_title: 'Eventos & Workshops',
      events_description: 'Eventos, workshops e atividades de fortalecimento comunitário.',
      events_impact: 'Eventos Anuais',
      events_details: 'Organizamos uma variedade de eventos incluindo workshops profissionais, celebrações culturais, noites de networking e seminários educacionais. Esses eventos criam oportunidades de conexão, aprendizado e celebração de nossa cultura.',
      
      volunteer_title: 'Programas de Voluntariado',
      volunteer_description: 'Oportunidades para contribuir e fazer a diferença juntos.',
      volunteer_impact: 'Voluntários Ativos',
      volunteer_details: 'Nossos programas de voluntariado oferecem oportunidades significativas de contribuir para nossa comunidade. Os voluntários apoiam nossos eventos, programas e iniciativas enquanto desenvolvem novas competências e criam conexões.',
      
      join_program_title: 'Pronto para participar dos nossos programas?',
      join_program_description: 'Seja para aprender, crescer o seu negócio ou conectar, temos um programa para si.',
      join_program_button: 'Tornar-se Membro'
    },
    partners: {
      badge: 'Nossos Parceiros',
      title: 'Construindo Juntos',
      description: 'Colaboramos com organizações que partilham nossa visão de capacitação e desenvolvimento comunitário.',
      partner_type_corporate: 'Parceiros Corporativos',
      partner_type_community: 'Organizações Comunitárias',
      partner_type_educational: 'Instituições Educacionais',
      partner_type_government: 'Agências Governamentais',
      become_partner_title: 'Torne-se Parceiro',
      become_partner_desc: 'Interessado em colaborar com CENA? Contacte-nos para explorar oportunidades de parceria.',
      become_partner_button: 'Contacte-nos'
    },
    members: {
      badge: 'Nossos Membros',
      title: 'Uma comunidade diversificada',
      description: 'Nossos membros vêm de diversas origens, unidos por um compromisso compartilhado com educação, empreendedorismo e desenvolvimento comunitário.',
      member_benefits: 'Benefícios para Membros',
      benefit1: 'Acesso a todos os programas e workshops',
      benefit2: 'Oportunidades de networking',
      benefit3: 'Mentoria e apoio',
      benefit4: 'Recursos empresariais',
      benefit5: 'Eventos comunitários',
      benefit6: 'Newsletter e atualizações',
      join_title: 'Junte-se à Nossa Comunidade',
      join_desc: 'Torne-se membro da CENA e conecte-se com pessoas que pensam da mesma forma e estão comprometidas em fazer a diferença.',
      join_button: 'Tornar-se Membro'
    },
    events: {
      badge: 'Eventos',
      title: 'Próximos Eventos',
      description: 'Junte-se a nós nos nossos eventos regulares projetados para educar, conectar e inspirar nossa comunidade.',
      upcoming: 'Próximos Eventos',
      event1_title: 'Workshop Desenvolvimento Empresarial',
      event1_location: 'Centro Comunitário de Montreal',
      coming_soon: 'Em Breve',
      event1_description: 'Aprenda estratégias essenciais para crescer o seu negócio no Canadá.',
      event1_attendees: '40 Vagas',
      event2_title: 'Noite de Networking',
      event2_location: 'Espaço CENA',
      event2_description: 'Conecte-se com profissionais e empreendedores da nossa comunidade.',
      event2_attendees: '60 Participantes',
      event3_title: 'Celebração Cultural',
      event3_location: 'Centro Comunitário',
      event3_description: 'Celebre a cultura angolana e lusófona com música, comida e dança.',
      event3_attendees: '150 Convidados',
      type_workshop: 'Workshop',
      type_networking: 'Networking',
      type_cultural: 'Cultural',
      register_now: 'Inscrever-se',
      past_events: 'Eventos Passados',
      past_event_success: 'Mais de 500 participantes nos nossos eventos este ano'
    },
    team: {
      badge: 'Nossa Equipe',
      title: 'Conheça Nossa Liderança',
      description: 'Nossa equipe de liderança dedicada guia a CENA em sua missão de capacitar a diáspora angolana e lusófona no Canadá.',
      role_president: 'Presidente / PDG',
      role_vp_operations: 'Vice-Presidente das Operações',
      role_finance: 'Diretor de Finanças',
      role_communication: 'Diretora de Comunicação & Mídias',
      role_business: 'Diretor de Desenvolvimento Comercial',
      role_training: 'Diretora de Formação & Mentorat',
      role_hr: 'Diretora de Recursos Humanos',
      role_international: 'Diretora de Relações Internacionais',
      role_events: 'Diretora de Eventos & Engajamento',
      role_youth: 'Diretor de Juventude & Inovação',
      leadership_title: 'Mensagem de Liderança',
      leadership_message: 'Juntos, construímos uma comunidade forte, unida pela educação, empreendedorismo e networking. Nosso compromisso é criar oportunidades que transformam vidas e fortalecem os laços comunitários em todo o Canadá e além.'
    },
    support: {
      badge: 'Apoie-nos',
      title: 'Ajude-nos a Causar Impacto',
      description: 'Seu apoio nos ajuda a expandir nossos programas e alcançar mais membros da comunidade. Há muitas maneiras de contribuir.',
      donate_title: 'Fazer uma Doação',
      donate_description: 'Seu apoio financeiro alimenta nossos programas e iniciativas.',
      choose_amount: 'Escolher Valor ($)',
      custom_amount: 'Valor personalizado',
      donation_message: 'Mensagem de Doação (Opcional)',
      donation_message_placeholder: 'Deixe uma mensagem de apoio...',
      tax_notice: 'Recibos fiscais estão disponíveis para doações elegíveis.',
      secure_payment: 'Pagamento seguro via PayPal • Redireciona para PayPal.com',
      other_ways: 'Outras Formas de Ajudar',
      volunteer_title: 'Voluntariado',
      volunteer_description: 'Junte-se à nossa equipe de voluntários e contribua diretamente para nossos programas.',
      sponsor_title: 'Patrocínio',
      sponsor_description: 'Patrocine um evento ou programa e ganhe visibilidade para sua marca.',
      impact_title: 'Seu Impacto',
      impact_50: 'Apoia um participante de workshop',
      impact_100: 'Financia um evento de networking',
      impact_250: 'Patrocina uma sessão de mentoria',
      impact_500: 'Apoia um programa completo'
    },
    blog: {
      badge: 'Blog & Notícias',
      title: 'Últimas Notícias',
      description: 'Mantenha-se informado sobre nossos últimos programas, eventos e histórias de sucesso comunitário.',
      read_full: 'Ler Artigo Completo',
      view_all_posts: 'Ver Todos os Artigos',
      article1_title: 'Programa de Empreendedorismo',
      article1_excerpt: 'CENA lança programa de empreendedorismo para apoiar empresas angolanas e lusófonas no Canadá.',
      article1_full: 'Nosso novo programa de empreendedorismo fornece aos empresários aspirantes e estabelecidos os recursos, mentoria e conexões necessárias para ter sucesso no cenário empresarial canadiano. O programa inclui workshops mensais, oportunidades de mentoria individual, acesso a especialistas da indústria e eventos de networking que conectam empreendedores com potenciais clientes e parceiros. Estamos entusiasmados em apoiar o crescimento de negócios comunitários e contribuir para o sucesso económico da nossa diáspora.',
      article1_author: 'Equipa CENA',
      article1_read_time: '4 min de leitura',
      article1_category: 'Programas',
      posted: 'Publicado',
      article2_title: 'Noite de Networking Record',
      article2_excerpt: 'Mais de 80 profissionais reuniram-se no nosso maior evento de networking, criando conexões significativas.',
      article2_full: 'Nossa recente noite de networking foi um sucesso retumbante, com mais de 80 profissionais de várias indústrias reunindo-se para conectar, compartilhar ideias e explorar oportunidades de colaboração. O evento apresentou sessões de networking estruturadas, painéis de discussão e apresentações de negócios locais. Os participantes expressaram apreço pela qualidade das conexões feitas e pela energia positiva da noite. Aguardamos ansiosamente por organizar mais eventos desta escala.',
      article2_author: 'Equipa CENA',
      article2_read_time: '3 min de leitura',
      article2_category: 'Eventos',
      article3_title: 'Novas Parcerias Educacionais',
      article3_excerpt: 'CENA faz parceria com três instituições educacionais para expandir o acesso a programas de formação.',
      article3_full: 'Estamos entusiasmados em anunciar novas parcerias com três instituições educacionais líderes que permitirão aos membros da CENA aceder a programas de formação especializados, workshops de desenvolvimento profissional e recursos de aprendizagem online. Estas parcerias refletem nosso compromisso em fornecer oportunidades educacionais de alta qualidade à nossa comunidade e apoiar a aprendizagem ao longo da vida. Detalhes adicionais sobre programas específicos serão anunciados em breve.',
      article3_author: 'Equipa CENA',
      article3_read_time: '3 min de leitura',
      article3_category: 'Parcerias',
      testimonial1_name: 'Ana Ferreira',
      testimonial1_role: 'Empreendedora',
      testimonial1_quote: 'CENA forneceu-me a mentoria e conexões que precisava para lançar meu negócio com sucesso no Canadá.',
      testimonial2_name: 'Carlos Mendes',
      testimonial2_role: 'Membro',
      testimonial2_quote: 'A comunidade e oportunidades de networking na CENA têm sido inestimáveis para meu crescimento profissional.',
      testimonial3_name: 'Miguel Santos',
      testimonial3_role: 'Desenvolvedor',
      testimonial3_quote: 'Os workshops técnicos e eventos de networking ajudaram-me a acelerar minha carreira no setor tecnológico canadiano.',
      testimonial4_name: 'Beatriz Lima',
      testimonial4_role: 'Consultora',
      testimonial4_quote: 'A integração no Canadá foi desafiadora, mas a CENA forneceu-me as ferramentas e o apoio para prosperar profissionalmente.',
      success_stories: 'Histórias de Sucesso',
      newsletter_title: 'Mantenha-se Conectado',
      newsletter_description: 'Inscreva-se na nossa newsletter para receber atualizações sobre nossos programas e eventos.',
      email_placeholder: 'Digite seu email',
      subscribe_button: 'Inscrever-se'
    },
    success: {
      badge: 'Testemunhos',
      title: 'Histórias de Sucesso',
      description: 'Descubra como a CENA transforma vidas através da educação, empreendedorismo e networking.',
      
      antonio_role: 'Chef',
      antonio_story: 'Graças à CENA, aperfeiçoei minhas habilidades e abri meu restaurante.',
      fernando_role: 'Pizzaiolo',
      fernando_story: 'A rede CENA me permitiu lançar minha pizzaria artesanal.',
      miguel_role: 'Pasteleiro',
      miguel_story: 'CENA transformou minha paixão em negócio próspero.',
      beatriz_role: 'Enfermeira',
      beatriz_story: 'CENA me guiou para reconhecer minhas qualificações.',
      carla_role: 'Médica',
      carla_story: 'O mentoring foi crucial para estabelecer minha prática médica.',
      joaquina_role: 'Restauradora',
      joaquina_story: 'CENA me conectou com parceiros para realizar meu sonho.',
      torres_role: 'Padeiro',
      torres_story: 'A formação me permitiu criar uma padaria próspera.',
      manuel_role: 'Merceeiro',
      manuel_story: 'CENA me ajudou a compreender o mercado e abrir minha loja.',
      domingos_role: 'Barbeiro',
      domingos_story: 'Graças à CENA, lancei meu salão e formei jovens.',
      isabel_role: 'Designer',
      isabel_story: 'CENA me conectou com clientes para minha agência.',
      alberto_role: 'Marceneiro',
      alberto_story: 'O programa me permitiu transformar meu saber-fazer.',
      rui_role: 'Gestor',
      rui_story: 'CENA me formou nos padrões e agora dirijo uma equipe.',
      jose_role: 'Consultor',
      jose_story: 'O mentoring acelerou minha transição para consultoria.',
      madalena_role: 'Diretora de Vendas',
      madalena_story: 'CENA me deu ferramentas para liderar uma equipe de alto desempenho.',
      francisca_role: 'Artesã',
      francisca_story: 'CENA me ajudou a comercializar minhas criações artesanais.',
      catarino_role: 'Estilista',
      catarino_story: 'A rede me conectou com clientes para minha linha.',
      agostinho_role: 'Consultor de Seguros',
      agostinho_story: 'CENA me ajudou a obter certificações e construir clientela.',
      henriques_role: 'Analista Financeiro',
      henriques_story: 'O programa me preparou para o setor financeiro.',
      bernardo_role: 'Contador',
      bernardo_story: 'CENA me apoiou na jornada CPA com sucesso.',
      vitoria_role: 'Agente Imobiliária',
      vitoria_story: 'CENA me ajudou a desenvolver minha experiência em imóveis.',
      selma_role: 'Especialista Marketing',
      selma_story: 'CENA abriu portas e agora lidero campanhas.',
      felicidade_role: 'Empreendedora Tech',
      felicidade_story: 'O programa de incubação me permitiu lançar minha startup.',
      mario_role: 'Desenvolvedor',
      mario_story: 'CENA me conectou com oportunidades tech.',
      xavier_role: 'Advogado',
      xavier_story: 'CENA me ajudou a construir minha prática jurídica e rede.',
      paulo_role: 'Advogado',
      paulo_story: 'A rede CENA me ajudou a estabelecer meu escritório e servir a comunidade.'
    },
    gallery: {
      badge: 'Galeria',
      title: 'Evento de Natal',
      subtitle: 'Destaques da nossa última celebração',
      view_all: 'Ver todas as fotos'
    },
    footer: {
      get_in_touch: 'Entre em Contato',
      our_location: 'Nossa Localização',
      location_text: '3181 Montée Saint-hubert, QC, Canadá\\nCENA - Comunidade de Educação e Networking Angolana\\nOrganização Comunitária',
      phone: 'Telefone',
      email: 'Email',
      about_cena: 'Sobre CENA',
      about_text: 'O CENA é reconhecido como uma Organização Sem Fins Lucrativos (OBNL) pelas autoridades fiscais do Canadá e do Quebec. Número de registro: 1745968-8. As doações são dedutíveis nos impostos no Canadá e no Quebec.',
      send_message: 'Envie-nos uma Mensagem',
      your_name: 'Seu Nome',
      your_email: 'Seu Email',
      subject: 'Assunto',
      subject_placeholder: 'Selecione um assunto',
      subject_membership: 'Adesão',
      subject_volunteer: 'Voluntariado',
      subject_partnership: 'Parceria',
      subject_sponsorship: 'Patrocínio',
      subject_workshop: 'Workshop',
      subject_networking: 'Evento de Networking',
      subject_entrepreneurship: 'Programa de Empreendedorismo',
      subject_education: 'Programa Educacional',
      subject_other: 'Outro',
      your_message: 'Sua Mensagem',
      send_message_btn: 'Enviar Mensagem',
      sending: 'Enviando...',
      sent: 'Enviado!',
      form_success: 'Mensagem enviada com sucesso! Entraremos em contato em breve.',
      form_error: 'Por favor, preencha todos os campos',
      email_error: 'Por favor, insira um endereço de email válido',
      form_error_generic: 'Falha ao enviar mensagem. Por favor, tente novamente ou envie-nos um email diretamente.',
      quick_links: 'Links Rápidos',
      legal: 'Legal',
      privacy_policy: 'Política de Privacidade',
      terms_of_service: 'Termos de Serviço',
      description: 'Capacitar, conectar e transformar através da educação, empreendedorismo e networking colaborativo.',
      copyright: '© 2025 CENA - Comunidade de Educação e Networking Angolana (Canadá). Todos os direitos reservados.',
      built_with_love: 'Feito com ❤️ para nossa comunidade'
    }
  }
};